/* ============================================================================
   SupplyChainIQ - PHASE 1 : SYNTHETIC DATA FOUNDATION
   FILE    : 04_data_validation.sql
   PURPOSE : Prove the generated dataset is complete, referentially sound,
             realistically distributed and that the flagship scenario and its
             three intervention options are derivable from the raw records.

   READ-ONLY. This script never modifies data.

   All relative dates derive from PUBLIC.DATASET_METADATA.DATASET_ANCHOR_DATE
   (fixed constant DATE '2026-08-15'); CURRENT_DATE() is never used for
   business logic. It appears once, in V1, purely to report the session clock.

   Governed-window conventions used by validation (Phase 1 working definitions,
   NOT canonical metric definitions - those come later):
     - recent demand window      : anchor-30 .. anchor-1  (30 historical days)
     - critical customer horizon : anchor    .. anchor+14
     - latest inventory position : SNAPSHOT_DATE = DATASET_ANCHOR_DATE
   ============================================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SUPPLYCHAINIQ_DB;

/* ===========================================================================
   V1 : ENVIRONMENT
   =========================================================================== */
SELECT '=== V1 ENVIRONMENT ===' AS SECTION;

SELECT
  CURRENT_ROLE()                              AS ROLE_USED,
  CURRENT_WAREHOUSE()                         AS WAREHOUSE_USED,
  CURRENT_DATABASE()                          AS DATABASE_USED,
  m.DATASET_NAME,
  m.DATASET_ANCHOR_DATE,
  m.VERSION                                   AS DATASET_VERSION,
  m.GENERATED_AT,
  CURRENT_DATE()                              AS SESSION_CURRENT_DATE,
  CURRENT_TIMESTAMP()                         AS SESSION_TIMESTAMP,
  CURRENT_ACCOUNT()                           AS ACCOUNT,
  CURRENT_VERSION()                           AS SNOWFLAKE_VERSION,
  /* the anchor is a fixed project constant, so it may differ from the session
     clock; the session timezone explains any one-day offset */
  DATEDIFF(day, CURRENT_DATE(), m.DATASET_ANCHOR_DATE) AS ANCHOR_MINUS_SESSION_DATE_DAYS
FROM PUBLIC.DATASET_METADATA m
WHERE m.VERSION = 1;

SHOW PARAMETERS LIKE 'TIMEZONE' IN ACCOUNT;

/* ===========================================================================
   V2 : SCHEMAS AND TABLES
   =========================================================================== */
SELECT '=== V2 SCHEMAS AND TABLES ===' AS SECTION;

SELECT SCHEMA_NAME, COMMENT
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE CATALOG_NAME = 'SUPPLYCHAINIQ_DB'
  AND SCHEMA_NAME <> 'INFORMATION_SCHEMA'
ORDER BY SCHEMA_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, BYTES
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA, TABLE_NAME;

/* CURATED must still be empty at the end of Phase 1 */
SELECT 'CURATED must be empty in Phase 1'          AS CHECK_NAME,
       0                                            AS EXPECTED_OBJECTS,
       COUNT(*)                                     AS ACTUAL_OBJECTS,
       IFF(COUNT(*) = 0, 'PASS', 'FAIL')            AS RESULT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CURATED';

/* ===========================================================================
   V3 : ROW-COUNT VALIDATION AGAINST TARGET MINIMUMS
   =========================================================================== */
SELECT '=== V3 ROW COUNTS VS TARGETS ===' AS SECTION;

WITH counts AS (
  SELECT 'SAP_ERP.VENDOR_MASTER'               AS TABLE_FQN, 'Suppliers'            AS DATASET, 100     AS MIN_TARGET, (SELECT COUNT(*) FROM SAP_ERP.VENDOR_MASTER)               AS ROW_CNT
  UNION ALL SELECT 'SAP_ERP.MATERIAL_MASTER',              'Parts',                 1000,   (SELECT COUNT(*) FROM SAP_ERP.MATERIAL_MASTER)
  UNION ALL SELECT 'SAP_ERP.PLANT_MASTER',                 'Plants',                12,     (SELECT COUNT(*) FROM SAP_ERP.PLANT_MASTER)
  UNION ALL SELECT 'SAP_ERP.SUPPLIER_MATERIAL',            'Supplier-material map', 1,      (SELECT COUNT(*) FROM SAP_ERP.SUPPLIER_MATERIAL)
  UNION ALL SELECT 'SAP_ERP.PURCHASE_ORDER_LINES',         'PO lines',              50000,  (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES)
  UNION ALL SELECT 'TMS_LOGISTICS.CARRIER_MASTER',         'Carriers',              20,     (SELECT COUNT(*) FROM TMS_LOGISTICS.CARRIER_MASTER)
  UNION ALL SELECT 'TMS_LOGISTICS.SHIPMENTS',              'Shipment lines',        50000,  (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS)
  UNION ALL SELECT 'TMS_LOGISTICS.TRANSPORT_OPTIONS',      'Transport options',     1,      (SELECT COUNT(*) FROM TMS_LOGISTICS.TRANSPORT_OPTIONS)
  UNION ALL SELECT 'TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS','Transfer options',  1,      (SELECT COUNT(*) FROM TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS)
  UNION ALL SELECT 'WMS_INVENTORY.INVENTORY_SNAPSHOTS',    'Inventory snapshots',   100000, (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS)
  UNION ALL SELECT 'DEMAND_PLANNING.DEMAND_HISTORY',       'Demand records',        100000, (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY)
  UNION ALL SELECT 'CRM_ORDERS.CUSTOMER_MASTER',           'Customers',             500,    (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_MASTER)
  UNION ALL SELECT 'CRM_ORDERS.CUSTOMER_ORDER_LINES',      'Customer order lines',  50000,  (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES)
  UNION ALL SELECT 'SUPPLIER_PORTAL.SUPPLIER_SCORECARDS',  'Supplier scorecards',   1,      (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS)
  UNION ALL SELECT 'SUPPLIER_PORTAL.SUPPLIER_PROFILE',     'Supplier profiles',     100,    (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_PROFILE)
  UNION ALL SELECT 'DOCUMENTS.SUPPLIER_DOCUMENTS',         'Documents',             100,    (SELECT COUNT(*) FROM DOCUMENTS.SUPPLIER_DOCUMENTS)
)
SELECT DATASET, TABLE_FQN, MIN_TARGET, ROW_CNT,
       IFF(ROW_CNT >= MIN_TARGET, 'PASS', 'FAIL') AS RESULT
FROM counts
ORDER BY DATASET;

SELECT 'TOTAL MAJOR SYNTHETIC RECORDS' AS METRIC,
       (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES)
     + (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS)
     + (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS)
     + (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY)
     + (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES)
     + (SELECT COUNT(*) FROM SAP_ERP.VENDOR_MASTER)
     + (SELECT COUNT(*) FROM SAP_ERP.MATERIAL_MASTER)
     + (SELECT COUNT(*) FROM SAP_ERP.PLANT_MASTER)
     + (SELECT COUNT(*) FROM SAP_ERP.SUPPLIER_MATERIAL)
     + (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_MASTER)
     + (SELECT COUNT(*) FROM TMS_LOGISTICS.CARRIER_MASTER)
     + (SELECT COUNT(*) FROM TMS_LOGISTICS.TRANSPORT_OPTIONS)
     + (SELECT COUNT(*) FROM TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS)
     + (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS)
     + (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_PROFILE)
     + (SELECT COUNT(*) FROM DOCUMENTS.SUPPLIER_DOCUMENTS) AS TOTAL_ROWS;

/* ===========================================================================
   V4 : DISTINCT-KEY / GRAIN VALIDATION
   =========================================================================== */
SELECT '=== V4 DISTINCT KEYS AND GRAIN ===' AS SECTION;

SELECT 'Distinct purchase orders'          AS MEASURE, COUNT(DISTINCT PO_NUMBER)::VARCHAR AS VALUE FROM SAP_ERP.PURCHASE_ORDER_LINES
UNION ALL SELECT 'PO lines',                 COUNT(*)::VARCHAR FROM SAP_ERP.PURCHASE_ORDER_LINES
UNION ALL SELECT 'Avg lines per PO',         ROUND(COUNT(*) / COUNT(DISTINCT PO_NUMBER), 2)::VARCHAR FROM SAP_ERP.PURCHASE_ORDER_LINES
UNION ALL SELECT 'Max lines per PO',         (SELECT MAX(c)::VARCHAR FROM (SELECT COUNT(*) c FROM SAP_ERP.PURCHASE_ORDER_LINES GROUP BY PO_NUMBER))
UNION ALL SELECT 'Distinct shipments',       COUNT(DISTINCT SHIPMENT_ID)::VARCHAR FROM TMS_LOGISTICS.SHIPMENTS
UNION ALL SELECT 'Shipment lines',           COUNT(*)::VARCHAR FROM TMS_LOGISTICS.SHIPMENTS
UNION ALL SELECT 'Distinct customer orders', COUNT(DISTINCT ORDER_ID)::VARCHAR FROM CRM_ORDERS.CUSTOMER_ORDER_LINES
UNION ALL SELECT 'Customer order lines',     COUNT(*)::VARCHAR FROM CRM_ORDERS.CUSTOMER_ORDER_LINES
UNION ALL SELECT 'Supplier-material rows',   COUNT(*)::VARCHAR FROM SAP_ERP.SUPPLIER_MATERIAL
UNION ALL SELECT 'Supplier scorecard rows',  COUNT(*)::VARCHAR FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS
UNION ALL SELECT 'Transport options',        COUNT(*)::VARCHAR FROM TMS_LOGISTICS.TRANSPORT_OPTIONS
UNION ALL SELECT 'Interplant transfer options', COUNT(*)::VARCHAR FROM TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS
UNION ALL SELECT 'Inventory part-site combos', COUNT(DISTINCT SKU || '|' || SITE_ID)::VARCHAR FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS
UNION ALL SELECT 'Inventory snapshot dates',   COUNT(DISTINCT SNAPSHOT_DATE)::VARCHAR FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS
UNION ALL SELECT 'Demand part-location combos', COUNT(DISTINCT PART_ID || '|' || LOCATION_ID)::VARCHAR FROM DEMAND_PLANNING.DEMAND_HISTORY
UNION ALL SELECT 'Demand dates',               COUNT(DISTINCT DEMAND_DATE)::VARCHAR FROM DEMAND_PLANNING.DEMAND_HISTORY;

/* grain uniqueness: no duplicate business keys */
SELECT 'Duplicate PO_NUMBER+PO_LINE_NUMBER'        AS CHECK_NAME,
       COUNT(*) AS DUP_KEYS, IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM (SELECT PO_NUMBER, PO_LINE_NUMBER FROM SAP_ERP.PURCHASE_ORDER_LINES
      GROUP BY 1,2 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Duplicate SHIPMENT_ID+SHIPMENT_LINE_NUMBER', COUNT(*), IFF(COUNT(*) = 0, 'PASS', 'FAIL')
FROM (SELECT SHIPMENT_ID, SHIPMENT_LINE_NUMBER FROM TMS_LOGISTICS.SHIPMENTS
      GROUP BY 1,2 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Duplicate ORDER_ID+ORDER_LINE', COUNT(*), IFF(COUNT(*) = 0, 'PASS', 'FAIL')
FROM (SELECT ORDER_ID, ORDER_LINE FROM CRM_ORDERS.CUSTOMER_ORDER_LINES
      GROUP BY 1,2 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Duplicate SITE_ID+SKU+SNAPSHOT_DATE', COUNT(*), IFF(COUNT(*) = 0, 'PASS', 'FAIL')
FROM (SELECT SITE_ID, SKU, SNAPSHOT_DATE FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS
      GROUP BY 1,2,3 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Duplicate PART_ID+LOCATION_ID+DEMAND_DATE', COUNT(*), IFF(COUNT(*) = 0, 'PASS', 'FAIL')
FROM (SELECT PART_ID, LOCATION_ID, DEMAND_DATE FROM DEMAND_PLANNING.DEMAND_HISTORY
      GROUP BY 1,2,3 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'Duplicate DOCUMENT_ID', COUNT(*), IFF(COUNT(*) = 0, 'PASS', 'FAIL')
FROM (SELECT DOCUMENT_ID FROM DOCUMENTS.SUPPLIER_DOCUMENTS GROUP BY 1 HAVING COUNT(*) > 1);

/* ===========================================================================
   V5 : REFERENTIAL VALIDATION - canonical business-key orphans (expect 0)
   =========================================================================== */
SELECT '=== V5 REFERENTIAL ORPHANS (EXPECT 0) ===' AS SECTION;

WITH orphans AS (
  SELECT 'shipment -> supplier (SUPPLIER_CODE -> VENDOR_ID)' AS RELATIONSHIP,
         (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
           WHERE s.SUPPLIER_CODE IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID = s.SUPPLIER_CODE)) AS ORPHANS
  UNION ALL SELECT 'shipment -> part (ITEM_CODE -> MATERIAL_NO)',
         (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
           WHERE s.ITEM_CODE IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = s.ITEM_CODE))
  UNION ALL SELECT 'shipment -> plant (DESTINATION_SITE -> PLANT_CODE)',
         (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
           WHERE s.DESTINATION_SITE IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER p WHERE p.PLANT_CODE = s.DESTINATION_SITE))
  UNION ALL SELECT 'shipment -> carrier (CARRIER_CODE)',
         (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
           WHERE s.CARRIER_CODE IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM TMS_LOGISTICS.CARRIER_MASTER c WHERE c.CARRIER_CODE = s.CARRIER_CODE))
  UNION ALL SELECT 'shipment -> PO (PO_REF -> PO_NUMBER)',
         (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
           WHERE s.PO_REF IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM SAP_ERP.PURCHASE_ORDER_LINES p WHERE p.PO_NUMBER = s.PO_REF))
  UNION ALL SELECT 'shipment -> PO line (PO_REF + PO_LINE_REF)',
         (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
           WHERE s.PO_REF IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM SAP_ERP.PURCHASE_ORDER_LINES p
                              WHERE p.PO_NUMBER = s.PO_REF AND p.PO_LINE_NUMBER = s.PO_LINE_REF))
  UNION ALL SELECT 'PO line -> supplier (VENDOR_ID)',
         (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES p
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID = p.VENDOR_ID))
  UNION ALL SELECT 'PO line -> part (MATERIAL_NO)',
         (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES p
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = p.MATERIAL_NO))
  UNION ALL SELECT 'PO line -> plant (PLANT_CODE)',
         (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES p
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER pl WHERE pl.PLANT_CODE = p.PLANT_CODE))
  UNION ALL SELECT 'inventory -> part (SKU -> MATERIAL_NO)',
         (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = i.SKU))
  UNION ALL SELECT 'inventory -> plant (SITE_ID -> PLANT_CODE)',
         (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER p WHERE p.PLANT_CODE = i.SITE_ID))
  UNION ALL SELECT 'customer order -> customer (CUSTOMER_ID)',
         (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c
           WHERE NOT EXISTS (SELECT 1 FROM CRM_ORDERS.CUSTOMER_MASTER cm WHERE cm.CUSTOMER_ID = c.CUSTOMER_ID))
  UNION ALL SELECT 'customer order -> part (PART_NUMBER -> MATERIAL_NO)',
         (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = c.PART_NUMBER))
  UNION ALL SELECT 'customer order -> plant (FULFILLMENT_SITE -> PLANT_CODE)',
         (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER p WHERE p.PLANT_CODE = c.FULFILLMENT_SITE))
  UNION ALL SELECT 'demand -> part (PART_ID -> MATERIAL_NO)',
         (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY d
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = d.PART_ID))
  UNION ALL SELECT 'demand -> plant (LOCATION_ID -> PLANT_CODE)',
         (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY d
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER p WHERE p.PLANT_CODE = d.LOCATION_ID))
  UNION ALL SELECT 'scorecard -> supplier (SUPPLIER_ID -> VENDOR_ID)',
         (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS s
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID = s.SUPPLIER_ID))
  UNION ALL SELECT 'portal profile -> supplier (SUPPLIER_ID -> VENDOR_ID)',
         (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_PROFILE s
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID = s.SUPPLIER_ID))
  UNION ALL SELECT 'supplier-material -> supplier (VENDOR_ID)',
         (SELECT COUNT(*) FROM SAP_ERP.SUPPLIER_MATERIAL sm
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID = sm.VENDOR_ID))
  UNION ALL SELECT 'supplier-material -> part (MATERIAL_NO)',
         (SELECT COUNT(*) FROM SAP_ERP.SUPPLIER_MATERIAL sm
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = sm.MATERIAL_NO))
  UNION ALL SELECT 'document -> supplier (supplier-specific docs only)',
         (SELECT COUNT(*) FROM DOCUMENTS.SUPPLIER_DOCUMENTS d
           WHERE d.SUPPLIER_ID IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID = d.SUPPLIER_ID))
  UNION ALL SELECT 'transport option -> plant (DESTINATION_PLANT)',
         (SELECT COUNT(*) FROM TMS_LOGISTICS.TRANSPORT_OPTIONS t
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER p WHERE p.PLANT_CODE = t.DESTINATION_PLANT))
  UNION ALL SELECT 'transfer option -> plants (ORIGIN/DESTINATION_PLANT)',
         (SELECT COUNT(*) FROM TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS t
           WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER p WHERE p.PLANT_CODE = t.ORIGIN_PLANT)
              OR NOT EXISTS (SELECT 1 FROM SAP_ERP.PLANT_MASTER p WHERE p.PLANT_CODE = t.DESTINATION_PLANT))
)
SELECT RELATIONSHIP, ORPHANS, IFF(ORPHANS = 0, 'PASS', 'FAIL') AS RESULT
FROM orphans
ORDER BY ORPHANS DESC, RELATIONSHIP;

SELECT 'TOTAL CANONICAL BUSINESS-KEY ORPHANS' AS CHECK_NAME,
       (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
         WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PURCHASE_ORDER_LINES p
                            WHERE p.PO_NUMBER = s.PO_REF AND p.PO_LINE_NUMBER = s.PO_LINE_REF))
     + (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES p
         WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID = p.VENDOR_ID))
     + (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
         WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = i.SKU))
     + (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c
         WHERE NOT EXISTS (SELECT 1 FROM CRM_ORDERS.CUSTOMER_MASTER cm WHERE cm.CUSTOMER_ID = c.CUSTOMER_ID))
     + (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY d
         WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = d.PART_ID))
       AS TOTAL_ORPHANS;

/* inventory / demand coverage alignment (needed for future DOI) */
SELECT 'Inventory part-site combos WITHOUT demand history' AS CHECK_NAME,
       COUNT(*) AS COMBOS,
       IFF(COUNT(*) = 0, 'PASS', 'REVIEW') AS RESULT
FROM (SELECT DISTINCT SKU, SITE_ID FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS) i
WHERE NOT EXISTS (SELECT 1 FROM DEMAND_PLANNING.DEMAND_HISTORY d
                   WHERE d.PART_ID = i.SKU AND d.LOCATION_ID = i.SITE_ID);

/* ===========================================================================
   V6 : DISTRIBUTION VALIDATION
   =========================================================================== */
SELECT '=== V6 DISTRIBUTIONS ===' AS SECTION;

/* shipment timing mix */
WITH s AS (
  SELECT SHIPMENT_STATUS,
         ACTUAL_DELIVERY_DATE, EXPECTED_DELIVERY_DATE,
         SHIPPED_QTY, RECEIVED_QTY
  FROM TMS_LOGISTICS.SHIPMENTS
), t AS (
  SELECT COUNT(*) AS total,
         COUNT_IF(ACTUAL_DELIVERY_DATE IS NULL)                                   AS open_lines,
         COUNT_IF(ACTUAL_DELIVERY_DATE <  EXPECTED_DELIVERY_DATE)                 AS early_lines,
         COUNT_IF(ACTUAL_DELIVERY_DATE =  EXPECTED_DELIVERY_DATE)                 AS ontime_lines,
         COUNT_IF(ACTUAL_DELIVERY_DATE >  EXPECTED_DELIVERY_DATE)                 AS late_lines,
         COUNT_IF(RECEIVED_QTY > 0 AND RECEIVED_QTY < SHIPPED_QTY)                AS partial_lines,
         COUNT_IF(SHIPMENT_STATUS = 'IN_TRANSIT')                                 AS in_transit_lines
  FROM s
)
SELECT 'Shipment lines'            AS MEASURE, total::VARCHAR AS VALUE, NULL AS PCT FROM t
UNION ALL SELECT 'Early',        early_lines::VARCHAR,      ROUND(100.0 * early_lines / total, 2) FROM t
UNION ALL SELECT 'On time',      ontime_lines::VARCHAR,     ROUND(100.0 * ontime_lines / total, 2) FROM t
UNION ALL SELECT 'Late',         late_lines::VARCHAR,       ROUND(100.0 * late_lines / total, 2) FROM t
UNION ALL SELECT 'Not delivered (open)', open_lines::VARCHAR, ROUND(100.0 * open_lines / total, 2) FROM t
UNION ALL SELECT 'In transit',   in_transit_lines::VARCHAR, ROUND(100.0 * in_transit_lines / total, 2) FROM t
UNION ALL SELECT 'Partial (qty)', partial_lines::VARCHAR,   ROUND(100.0 * partial_lines / total, 2) FROM t;

SELECT SHIPMENT_STATUS, COUNT(*) AS LINES,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM TMS_LOGISTICS.SHIPMENTS GROUP BY 1 ORDER BY LINES DESC;

SELECT TRANSPORT_MODE, COUNT(*) AS LINES,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM TMS_LOGISTICS.SHIPMENTS GROUP BY 1 ORDER BY LINES DESC;

/* PO status mix - cancelled share must be ~3-5% */
SELECT PO_STATUS, COUNT(*) AS LINES,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM SAP_ERP.PURCHASE_ORDER_LINES GROUP BY 1 ORDER BY LINES DESC;

SELECT 'Cancelled PO line share' AS CHECK_NAME,
       '3% - 5%' AS EXPECTED,
       ROUND(100.0 * COUNT_IF(PO_STATUS = 'CANCELLED') / COUNT(*), 2) AS ACTUAL_PCT,
       IFF(100.0 * COUNT_IF(PO_STATUS = 'CANCELLED') / COUNT(*) BETWEEN 3 AND 5, 'PASS', 'REVIEW') AS RESULT
FROM SAP_ERP.PURCHASE_ORDER_LINES;

/* customer order mix */
SELECT ORDER_STATUS, COUNT(*) AS LINES,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PCT,
       SUM(ORDER_VALUE) AS ORDER_VALUE_INR
FROM CRM_ORDERS.CUSTOMER_ORDER_LINES GROUP BY 1 ORDER BY LINES DESC;

SELECT 'Partially fulfilled customer order lines' AS MEASURE,
       COUNT_IF(FULFILLED_QTY > 0 AND FULFILLED_QTY < ORDERED_QTY) AS LINES,
       ROUND(100.0 * COUNT_IF(FULFILLED_QTY > 0 AND FULFILLED_QTY < ORDERED_QTY) / COUNT(*), 2) AS PCT
FROM CRM_ORDERS.CUSTOMER_ORDER_LINES;

SELECT PRIORITY, COUNT(*) AS LINES,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM CRM_ORDERS.CUSTOMER_ORDER_LINES GROUP BY 1 ORDER BY LINES DESC;

/* master-data distributions */
SELECT 'Supplier tier' AS DIMENSION, VENDOR_TIER AS VALUE, COUNT(*) AS N FROM SAP_ERP.VENDOR_MASTER GROUP BY 1,2
UNION ALL SELECT 'Supplier status', VENDOR_STATUS, COUNT(*) FROM SAP_ERP.VENDOR_MASTER GROUP BY 1,2
UNION ALL SELECT 'Supplier region', REGION, COUNT(*) FROM SAP_ERP.VENDOR_MASTER GROUP BY 1,2
UNION ALL SELECT 'Part criticality', CRITICALITY, COUNT(*) FROM SAP_ERP.MATERIAL_MASTER GROUP BY 1,2
UNION ALL SELECT 'Product family', PRODUCT_FAMILY, COUNT(*) FROM SAP_ERP.MATERIAL_MASTER GROUP BY 1,2
UNION ALL SELECT 'Plant region', REGION, COUNT(*) FROM SAP_ERP.PLANT_MASTER GROUP BY 1,2
UNION ALL SELECT 'Customer segment', CUSTOMER_SEGMENT, COUNT(*) FROM CRM_ORDERS.CUSTOMER_MASTER GROUP BY 1,2
UNION ALL SELECT 'Customer priority tier', PRIORITY_TIER, COUNT(*) FROM CRM_ORDERS.CUSTOMER_MASTER GROUP BY 1,2
UNION ALL SELECT 'Carrier mode', TRANSPORT_MODE, COUNT(*) FROM TMS_LOGISTICS.CARRIER_MASTER GROUP BY 1,2
UNION ALL SELECT 'Document type', DOCUMENT_TYPE, COUNT(*) FROM DOCUMENTS.SUPPLIER_DOCUMENTS GROUP BY 1,2
ORDER BY DIMENSION, N DESC;

/* latest-snapshot inventory status mix */
SELECT i.INVENTORY_STATUS, COUNT(*) AS POSITIONS,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
JOIN PUBLIC.DATASET_METADATA m ON m.VERSION = 1 AND i.SNAPSHOT_DATE = m.DATASET_ANCHOR_DATE
GROUP BY 1 ORDER BY POSITIONS DESC;

/* supplier risk mix on the latest scorecard per supplier */
SELECT RISK_CATEGORY, COUNT(*) AS SUPPLIERS,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM (SELECT SUPPLIER_ID, RISK_CATEGORY
      FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS
      QUALIFY ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID ORDER BY SCORECARD_DATE DESC) = 1)
GROUP BY 1 ORDER BY SUPPLIERS DESC;

/* demand pattern mix */
SELECT DEMAND_PATTERN, COUNT(DISTINCT PART_ID || '|' || LOCATION_ID) AS COMBOS, COUNT(*) AS ROW_CNT
FROM DEMAND_PLANNING.DEMAND_HISTORY GROUP BY 1 ORDER BY COMBOS DESC;

/* multiple shipments against one PO line */
SELECT 'PO lines with >1 shipment line' AS MEASURE, COUNT(*) AS PO_LINES
FROM (SELECT PO_REF, PO_LINE_REF FROM TMS_LOGISTICS.SHIPMENTS
      GROUP BY 1,2 HAVING COUNT(*) > 1);

/* ===========================================================================
   V7 : FLAGSHIP SCENARIO PROOF  (S017 / P104 / P01)
   =========================================================================== */
SELECT '=== V7 FLAGSHIP SCENARIO ===' AS SECTION;

/* master data context */
SELECT v.VENDOR_ID, v.VENDOR_NAME, v.REGION, v.COUNTRY, v.VENDOR_TIER, v.VENDOR_STATUS
FROM SAP_ERP.VENDOR_MASTER v WHERE v.VENDOR_ID IN ('S017','S042');

SELECT MATERIAL_NO, MATERIAL_DESCRIPTION, PRODUCT_FAMILY, PRODUCT_CATEGORY,
       UNIT_OF_MEASURE, STANDARD_COST, CRITICALITY, ACTIVE_FLAG
FROM SAP_ERP.MATERIAL_MASTER WHERE MATERIAL_NO = 'P104';

SELECT PLANT_CODE, PLANT_NAME, REGION, COUNTRY, CAPACITY, PLANT_TYPE, ACTIVE_FLAG
FROM SAP_ERP.PLANT_MASTER WHERE PLANT_CODE IN ('P01','P03');

/* the delayed inbound purchase order and shipment */
SELECT p.PO_NUMBER, p.PO_LINE_NUMBER, p.VENDOR_ID, p.MATERIAL_NO, p.PLANT_CODE,
       p.ORDER_DATE, p.CONFIRMATION_DATE, p.PROMISED_DATE, p.ORDER_QTY,
       p.UNIT_PRICE, p.CURRENCY, p.PO_STATUS
FROM SAP_ERP.PURCHASE_ORDER_LINES p
WHERE p.VENDOR_ID = 'S017' AND p.MATERIAL_NO = 'P104' AND p.PLANT_CODE = 'P01'
  AND p.PO_STATUS = 'OPEN'
  AND p.PROMISED_DATE >= (SELECT DATASET_ANCHOR_DATE FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1)
ORDER BY p.PROMISED_DATE;

SELECT s.SHIPMENT_ID, s.SHIPMENT_LINE_NUMBER, s.PO_REF, s.PO_LINE_REF,
       s.SUPPLIER_CODE, s.ITEM_CODE, s.DESTINATION_SITE, s.CARRIER_CODE, s.TRANSPORT_MODE,
       s.SHIP_DATE, s.EXPECTED_DELIVERY_DATE, s.PROJECTED_DELIVERY_DATE, s.ACTUAL_DELIVERY_DATE,
       DATEDIFF(day, s.EXPECTED_DELIVERY_DATE, s.PROJECTED_DELIVERY_DATE) AS DELAY_DAYS,
       s.SHIPPED_QTY, s.RECEIVED_QTY, s.SHIPMENT_STATUS,
       s.FREIGHT_COST, s.DUTY_COST, s.HANDLING_COST, s.OTHER_LOGISTICS_COST
FROM TMS_LOGISTICS.SHIPMENTS s
WHERE s.SUPPLIER_CODE = 'S017' AND s.ITEM_CODE = 'P104' AND s.DESTINATION_SITE = 'P01'
  AND s.ACTUAL_DELIVERY_DATE IS NULL
ORDER BY s.PROJECTED_DELIVERY_DATE;

/* the three affected customer order lines */
SELECT c.ORDER_ID, c.ORDER_LINE, c.CUSTOMER_ID, cm.CUSTOMER_NAME, cm.CUSTOMER_SEGMENT,
       cm.PRIORITY_TIER, c.PART_NUMBER, c.FULFILLMENT_SITE, c.ORDER_DATE, c.DUE_DATE,
       c.ORDERED_QTY, c.FULFILLED_QTY, c.UNIT_SELL_PRICE, c.ORDER_VALUE,
       c.ORDER_STATUS, c.PRIORITY
FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c
JOIN CRM_ORDERS.CUSTOMER_MASTER cm ON cm.CUSTOMER_ID = c.CUSTOMER_ID
CROSS JOIN PUBLIC.DATASET_METADATA m
WHERE m.VERSION = 1
  AND c.PART_NUMBER = 'P104' AND c.FULFILLMENT_SITE = 'P01'
  AND c.ORDER_STATUS = 'OPEN'
  AND c.DUE_DATE BETWEEN m.DATASET_ANCHOR_DATE AND DATEADD(day, 14, m.DATASET_ANCHOR_DATE)
ORDER BY c.DUE_DATE;

/* the single consolidated proof row */
WITH a AS (
  SELECT DATASET_ANCHOR_DATE AS A FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1
),
inv AS (
  SELECT i.AVAILABLE_QTY, i.SAFETY_STOCK_QTY, i.ON_HAND_QTY, i.IN_TRANSIT_QTY
  FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i CROSS JOIN a
  WHERE i.SKU = 'P104' AND i.SITE_ID = 'P01' AND i.SNAPSHOT_DATE = a.A
),
dem AS (
  SELECT COUNT(*) AS DEMAND_DAYS, SUM(d.ACTUAL_DEMAND_QTY) AS DEMAND_30D,
         ROUND(AVG(d.ACTUAL_DEMAND_QTY), 2) AS AVG_DAILY_DEMAND
  FROM DEMAND_PLANNING.DEMAND_HISTORY d CROSS JOIN a
  WHERE d.PART_ID = 'P104' AND d.LOCATION_ID = 'P01'
    AND d.DEMAND_DATE BETWEEN DATEADD(day, -30, a.A) AND DATEADD(day, -1, a.A)
),
ord AS (
  SELECT COUNT(*) AS AFFECTED_ORDERS, SUM(c.ORDERED_QTY) AS CUSTOMER_REQUIREMENT,
         SUM(c.ORDER_VALUE) AS REVENUE_EXPOSURE_INR,
         MIN(c.DUE_DATE) AS FIRST_DUE_DATE, MAX(c.DUE_DATE) AS LAST_DUE_DATE
  FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c CROSS JOIN a
  WHERE c.PART_NUMBER = 'P104' AND c.FULFILLMENT_SITE = 'P01' AND c.ORDER_STATUS = 'OPEN'
    AND c.DUE_DATE BETWEEN a.A AND DATEADD(day, 14, a.A)
),
shp AS (
  SELECT s.SHIPMENT_ID, s.EXPECTED_DELIVERY_DATE, s.PROJECTED_DELIVERY_DATE,
         DATEDIFF(day, s.EXPECTED_DELIVERY_DATE, s.PROJECTED_DELIVERY_DATE) AS SHIPMENT_DELAY_DAYS,
         s.SHIPPED_QTY AS INBOUND_QTY
  FROM TMS_LOGISTICS.SHIPMENTS s
  WHERE s.SUPPLIER_CODE = 'S017' AND s.ITEM_CODE = 'P104' AND s.DESTINATION_SITE = 'P01'
    AND s.ACTUAL_DELIVERY_DATE IS NULL
  QUALIFY ROW_NUMBER() OVER (ORDER BY s.PROJECTED_DELIVERY_DATE) = 1
)
SELECT
  a.A                                                        AS DATASET_ANCHOR_DATE,
  inv.ON_HAND_QTY, inv.AVAILABLE_QTY, inv.SAFETY_STOCK_QTY,
  inv.AVAILABLE_QTY - inv.SAFETY_STOCK_QTY                   AS SAFE_USABLE_INVENTORY,
  dem.DEMAND_DAYS, dem.DEMAND_30D, dem.AVG_DAILY_DEMAND,
  ord.AFFECTED_ORDERS, ord.CUSTOMER_REQUIREMENT, ord.REVENUE_EXPOSURE_INR,
  ord.FIRST_DUE_DATE, ord.LAST_DUE_DATE,
  ord.CUSTOMER_REQUIREMENT - (inv.AVAILABLE_QTY - inv.SAFETY_STOCK_QTY) AS PROJECTED_SHORTAGE,
  shp.SHIPMENT_ID, shp.INBOUND_QTY,
  shp.EXPECTED_DELIVERY_DATE, shp.PROJECTED_DELIVERY_DATE, shp.SHIPMENT_DELAY_DAYS,
  /* the delayed inbound arrives after the last critical due date -> cannot rescue */
  IFF(shp.PROJECTED_DELIVERY_DATE > ord.LAST_DUE_DATE, 'YES', 'NO')     AS INBOUND_TOO_LATE
FROM a, inv, dem, ord, shp;

/* explicit assertions on the flagship numbers */
WITH a AS (SELECT DATASET_ANCHOR_DATE AS A FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1),
f AS (
  SELECT
    (SELECT i.AVAILABLE_QTY FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i CROSS JOIN a
      WHERE i.SKU='P104' AND i.SITE_ID='P01' AND i.SNAPSHOT_DATE=a.A)                AS avail,
    (SELECT i.SAFETY_STOCK_QTY FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i CROSS JOIN a
      WHERE i.SKU='P104' AND i.SITE_ID='P01' AND i.SNAPSHOT_DATE=a.A)                AS ss,
    (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c CROSS JOIN a
      WHERE c.PART_NUMBER='P104' AND c.FULFILLMENT_SITE='P01' AND c.ORDER_STATUS='OPEN'
        AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A))                          AS n_orders,
    (SELECT SUM(c.ORDERED_QTY) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c CROSS JOIN a
      WHERE c.PART_NUMBER='P104' AND c.FULFILLMENT_SITE='P01' AND c.ORDER_STATUS='OPEN'
        AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A))                          AS req,
    (SELECT SUM(c.ORDER_VALUE) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c CROSS JOIN a
      WHERE c.PART_NUMBER='P104' AND c.FULFILLMENT_SITE='P01' AND c.ORDER_STATUS='OPEN'
        AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A))                          AS exposure,
    (SELECT ROUND(AVG(d.ACTUAL_DEMAND_QTY),2) FROM DEMAND_PLANNING.DEMAND_HISTORY d CROSS JOIN a
      WHERE d.PART_ID='P104' AND d.LOCATION_ID='P01'
        AND d.DEMAND_DATE BETWEEN DATEADD(day,-30,a.A) AND DATEADD(day,-1,a.A))      AS add30,
    (SELECT MAX(DATEDIFF(day, s.EXPECTED_DELIVERY_DATE, s.PROJECTED_DELIVERY_DATE))
       FROM TMS_LOGISTICS.SHIPMENTS s
      WHERE s.SUPPLIER_CODE='S017' AND s.ITEM_CODE='P104' AND s.DESTINATION_SITE='P01'
        AND s.ACTUAL_DELIVERY_DATE IS NULL)                                          AS delay
)
SELECT 'AVAILABLE_QTY'        AS ASSERTION, '8200'    AS EXPECTED, avail::VARCHAR    AS ACTUAL, IFF(avail   = 8200,    'PASS','FAIL') AS RESULT FROM f
UNION ALL SELECT 'SAFETY_STOCK_QTY',        '3000',    ss::VARCHAR,                        IFF(ss      = 3000,    'PASS','FAIL') FROM f
UNION ALL SELECT 'SAFE_USABLE_INVENTORY',   '5200',    (avail-ss)::VARCHAR,                IFF(avail-ss= 5200,    'PASS','FAIL') FROM f
UNION ALL SELECT 'AFFECTED_CUSTOMER_ORDERS','3',       n_orders::VARCHAR,                  IFF(n_orders= 3,       'PASS','FAIL') FROM f
UNION ALL SELECT 'CUSTOMER_REQUIREMENT',    '7350',    req::VARCHAR,                       IFF(req     = 7350,    'PASS','FAIL') FROM f
UNION ALL SELECT 'PROJECTED_SHORTAGE',      '2150',    (req-(avail-ss))::VARCHAR,          IFF(req-(avail-ss)=2150,'PASS','FAIL') FROM f
UNION ALL SELECT 'REVENUE_EXPOSURE_INR',    '4200000', exposure::VARCHAR,                  IFF(exposure= 4200000, 'PASS','FAIL') FROM f
UNION ALL SELECT 'AVG_DAILY_DEMAND_30D',    '~700',    add30::VARCHAR,                     IFF(add30 BETWEEN 660 AND 740,'PASS','FAIL') FROM f
UNION ALL SELECT 'SHIPMENT_DELAY_DAYS',     '5',       delay::VARCHAR,                     IFF(delay   = 5,       'PASS','FAIL') FROM f;

/* S017 vs S042 sourcing comparison for P104 */
SELECT sm.VENDOR_ID, v.VENDOR_NAME, v.VENDOR_STATUS, sm.IS_PRIMARY_SUPPLIER,
       sm.AGREED_UNIT_PRICE, sm.CURRENCY, sm.CONTRACT_LEAD_TIME_DAYS,
       sm.MINIMUM_ORDER_QTY, sm.MAX_WEEKLY_SUPPLY_QTY, sm.VALID_FROM, sm.VALID_TO
FROM SAP_ERP.SUPPLIER_MATERIAL sm
JOIN SAP_ERP.VENDOR_MASTER v ON v.VENDOR_ID = sm.VENDOR_ID
WHERE sm.MATERIAL_NO = 'P104'
ORDER BY sm.IS_PRIMARY_SUPPLIER DESC;

/* ===========================================================================
   V8 : RESPONSE-OPTION VALIDATION (facts only - no recommendation logic)
   =========================================================================== */
SELECT '=== V8 INTERVENTION OPTIONS ===' AS SECTION;

/* OPTION 1 - EXPEDITE */
SELECT
  t.ORIGIN_REGION, t.DESTINATION_PLANT, t.TRANSPORT_MODE,
  t.NORMAL_TRANSIT_DAYS, t.EXPEDITED_TRANSIT_DAYS,
  t.NORMAL_COST_FACTOR, t.EXPEDITE_COST_FACTOR, t.ACTIVE_FLAG,
  m.DATASET_ANCHOR_DATE                                                   AS ANCHOR,
  DATEADD(day, t.EXPEDITED_TRANSIT_DAYS, m.DATASET_ANCHOR_DATE)           AS EXPEDITED_ARRIVAL_DATE,
  DATEADD(day, 12, m.DATASET_ANCHOR_DATE)                                 AS FIRST_ORDER_DUE_DATE,
  IFF(DATEADD(day, t.EXPEDITED_TRANSIT_DAYS, m.DATASET_ANCHOR_DATE)
        < DATEADD(day, 12, m.DATASET_ANCHOR_DATE), 'YES', 'NO')           AS ARRIVES_BEFORE_FIRST_DUE_DATE
FROM TMS_LOGISTICS.TRANSPORT_OPTIONS t
CROSS JOIN PUBLIC.DATASET_METADATA m
JOIN SAP_ERP.VENDOR_MASTER v ON v.VENDOR_ID = 'S017' AND v.REGION = t.ORIGIN_REGION
WHERE m.VERSION = 1 AND t.DESTINATION_PLANT = 'P01' AND t.ACTIVE_FLAG
ORDER BY t.EXPEDITED_TRANSIT_DAYS;

SELECT 'Expedite option exists for S017 region -> P01' AS CHECK_NAME,
       COUNT(*) AS ACTIVE_LANES,
       IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS RESULT
FROM TMS_LOGISTICS.TRANSPORT_OPTIONS t
JOIN SAP_ERP.VENDOR_MASTER v ON v.VENDOR_ID = 'S017' AND v.REGION = t.ORIGIN_REGION
WHERE t.DESTINATION_PLANT = 'P01' AND t.ACTIVE_FLAG
  AND t.EXPEDITED_TRANSIT_DAYS < t.NORMAL_TRANSIT_DAYS
  AND t.EXPEDITE_COST_FACTOR > t.NORMAL_COST_FACTOR;

/* OPTION 2 - INTERPLANT TRANSFER P03 -> P01 */
WITH a AS (SELECT DATASET_ANCHOR_DATE AS A FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1),
p03 AS (
  SELECT i.AVAILABLE_QTY, i.SAFETY_STOCK_QTY,
         i.AVAILABLE_QTY - i.SAFETY_STOCK_QTY AS SAFELY_TRANSFERABLE
  FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i CROSS JOIN a
  WHERE i.SKU = 'P104' AND i.SITE_ID = 'P03' AND i.SNAPSHOT_DATE = a.A
)
SELECT 'P03' AS ORIGIN_PLANT, 'P01' AS DESTINATION_PLANT, 'P104' AS PART,
       p03.AVAILABLE_QTY AS P03_AVAILABLE_QTY,
       p03.SAFETY_STOCK_QTY AS P03_SAFETY_STOCK,
       p03.SAFELY_TRANSFERABLE,
       o.TRANSPORT_MODE, o.TRANSIT_DAYS, o.COST_PER_UNIT, o.FIXED_TRANSFER_COST,
       o.MAX_TRANSFER_QTY, o.ACTIVE_FLAG,
       LEAST(p03.SAFELY_TRANSFERABLE, o.MAX_TRANSFER_QTY) AS FEASIBLE_TRANSFER_QTY,
       2150                                                AS SHORTAGE_TO_COVER,
       ROUND(2150 * o.COST_PER_UNIT + o.FIXED_TRANSFER_COST, 2) AS COST_TO_COVER_SHORTAGE,
       DATEADD(day, o.TRANSIT_DAYS, a.A)                   AS TRANSFER_ARRIVAL_DATE,
       DATEADD(day, 12, a.A)                               AS FIRST_ORDER_DUE_DATE,
       IFF(DATEADD(day, o.TRANSIT_DAYS, a.A) < DATEADD(day, 12, a.A), 'YES', 'NO') AS ARRIVES_BEFORE_FIRST_DUE_DATE,
       IFF(LEAST(p03.SAFELY_TRANSFERABLE, o.MAX_TRANSFER_QTY) >= 2150, 'PASS', 'FAIL') AS RESULT
FROM TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS o, p03, a
WHERE o.ORIGIN_PLANT = 'P03' AND o.DESTINATION_PLANT = 'P01' AND o.ACTIVE_FLAG;

/* OPTION 3 - ALTERNATE SUPPLIER S042 */
WITH a AS (SELECT DATASET_ANCHOR_DATE AS A FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1),
sc AS (
  SELECT SUPPLIER_ID, QUALITY_SCORE, REJECTION_RATE, REPORTED_LEAD_TIME_DAYS,
         LEAD_TIME_VARIABILITY, SERVICE_SCORE, RISK_CATEGORY, OPEN_ISSUE_COUNT
  FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID ORDER BY SCORECARD_DATE DESC) = 1
)
SELECT sm.VENDOR_ID, v.VENDOR_NAME, v.VENDOR_STATUS, sm.IS_PRIMARY_SUPPLIER,
       sm.AGREED_UNIT_PRICE, sm.CURRENCY, sm.CONTRACT_LEAD_TIME_DAYS,
       sm.MAX_WEEKLY_SUPPLY_QTY,
       sc.RISK_CATEGORY, sc.SERVICE_SCORE, sc.QUALITY_SCORE, sc.REJECTION_RATE,
       sc.REPORTED_LEAD_TIME_DAYS, sc.LEAD_TIME_VARIABILITY, sc.OPEN_ISSUE_COUNT,
       DATEADD(day, sm.CONTRACT_LEAD_TIME_DAYS, a.A) AS ALT_SOURCE_ARRIVAL_DATE,
       DATEADD(day, 12, a.A)                         AS FIRST_ORDER_DUE_DATE,
       IFF(DATEADD(day, sm.CONTRACT_LEAD_TIME_DAYS, a.A) < DATEADD(day, 12, a.A), 'YES','NO') AS ARRIVES_BEFORE_FIRST_DUE_DATE,
       IFF(sm.MAX_WEEKLY_SUPPLY_QTY >= 2150, 'PASS', 'FAIL') AS CAPACITY_RESULT
FROM SAP_ERP.SUPPLIER_MATERIAL sm
JOIN SAP_ERP.VENDOR_MASTER v ON v.VENDOR_ID = sm.VENDOR_ID
LEFT JOIN sc ON sc.SUPPLIER_ID = sm.VENDOR_ID
CROSS JOIN a
WHERE sm.MATERIAL_NO = 'P104'
ORDER BY sm.IS_PRIMARY_SUPPLIER DESC;

/* S017 vs S042 delivery reliability from actual shipment history */
SELECT s.SUPPLIER_CODE,
       COUNT(*)                                                              AS DELIVERED_LINES,
       COUNT_IF(s.ACTUAL_DELIVERY_DATE <= p.PROMISED_DATE)                   AS ON_TIME_LINES,
       ROUND(100.0 * COUNT_IF(s.ACTUAL_DELIVERY_DATE <= p.PROMISED_DATE) / COUNT(*), 2) AS OTD_PCT,
       ROUND(AVG(DATEDIFF(day, p.ORDER_DATE, s.ACTUAL_DELIVERY_DATE)), 2)    AS AVG_LEAD_TIME_DAYS,
       ROUND(STDDEV(DATEDIFF(day, p.ORDER_DATE, s.ACTUAL_DELIVERY_DATE)), 2) AS LEAD_TIME_STDDEV
FROM TMS_LOGISTICS.SHIPMENTS s
JOIN SAP_ERP.PURCHASE_ORDER_LINES p
  ON p.PO_NUMBER = s.PO_REF AND p.PO_LINE_NUMBER = s.PO_LINE_REF
WHERE s.SUPPLIER_CODE IN ('S017','S042')
  AND s.ACTUAL_DELIVERY_DATE IS NOT NULL
  AND p.PO_STATUS <> 'CANCELLED'
GROUP BY 1 ORDER BY 1;

/* documentary evidence available for the scenario */
SELECT DOCUMENT_ID, SUPPLIER_ID, DOCUMENT_TYPE, TITLE, EFFECTIVE_DATE, EXPIRY_DATE,
       LENGTH(CONTENT) AS CONTENT_CHARS,
       IFF(EXPIRY_DATE >= (SELECT DATASET_ANCHOR_DATE FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1),
           'ACTIVE', 'EXPIRED') AS STATUS
FROM DOCUMENTS.SUPPLIER_DOCUMENTS
WHERE SUPPLIER_ID IN ('S017','S042')
ORDER BY SUPPLIER_ID, DOCUMENT_TYPE;

/* ===========================================================================
   V9 : METRIC-READINESS MATRIX (source fields only - no metric definitions)
   =========================================================================== */
SELECT '=== V9 METRIC READINESS ===' AS SECTION;

WITH required AS (
  SELECT * FROM VALUES
    ('OTD',                'SAP_ERP',        'PURCHASE_ORDER_LINES','PROMISED_DATE'),
    ('OTD',                'SAP_ERP',        'PURCHASE_ORDER_LINES','PO_STATUS'),
    ('OTD',                'TMS_LOGISTICS',  'SHIPMENTS',           'ACTUAL_DELIVERY_DATE'),
    ('OTD',                'TMS_LOGISTICS',  'SHIPMENTS',           'PO_LINE_REF'),
    ('Fill Rate',          'CRM_ORDERS',     'CUSTOMER_ORDER_LINES','ORDERED_QTY'),
    ('Fill Rate',          'CRM_ORDERS',     'CUSTOMER_ORDER_LINES','FULFILLED_QTY'),
    ('Fill Rate',          'CRM_ORDERS',     'CUSTOMER_ORDER_LINES','ORDER_STATUS'),
    ('Days of Inventory',  'WMS_INVENTORY',  'INVENTORY_SNAPSHOTS', 'AVAILABLE_QTY'),
    ('Days of Inventory',  'WMS_INVENTORY',  'INVENTORY_SNAPSHOTS', 'SNAPSHOT_DATE'),
    ('Days of Inventory',  'DEMAND_PLANNING','DEMAND_HISTORY',      'ACTUAL_DEMAND_QTY'),
    ('Days of Inventory',  'DEMAND_PLANNING','DEMAND_HISTORY',      'DEMAND_DATE'),
    ('Landed Cost',        'SAP_ERP',        'PURCHASE_ORDER_LINES','UNIT_PRICE'),
    ('Landed Cost',        'SAP_ERP',        'PURCHASE_ORDER_LINES','ORDER_QTY'),
    ('Landed Cost',        'TMS_LOGISTICS',  'SHIPMENTS',           'FREIGHT_COST'),
    ('Landed Cost',        'TMS_LOGISTICS',  'SHIPMENTS',           'DUTY_COST'),
    ('Landed Cost',        'TMS_LOGISTICS',  'SHIPMENTS',           'HANDLING_COST'),
    ('Landed Cost',        'TMS_LOGISTICS',  'SHIPMENTS',           'OTHER_LOGISTICS_COST'),
    ('Lead Time',          'SAP_ERP',        'PURCHASE_ORDER_LINES','ORDER_DATE'),
    ('Lead Time',          'SAP_ERP',        'PURCHASE_ORDER_LINES','CONFIRMATION_DATE'),
    ('Lead Time',          'TMS_LOGISTICS',  'SHIPMENTS',           'ACTUAL_DELIVERY_DATE'),
    ('Lead Time',          'SAP_ERP',        'SUPPLIER_MATERIAL',   'CONTRACT_LEAD_TIME_DAYS'),
    ('Inventory Turnover', 'WMS_INVENTORY',  'INVENTORY_SNAPSHOTS', 'ON_HAND_QTY'),
    ('Inventory Turnover', 'DEMAND_PLANNING','DEMAND_HISTORY',      'ACTUAL_DEMAND_QTY'),
    ('Inventory Turnover', 'SAP_ERP',        'MATERIAL_MASTER',     'STANDARD_COST'),
    ('Supplier Risk Score','SUPPLIER_PORTAL','SUPPLIER_SCORECARDS', 'QUALITY_SCORE'),
    ('Supplier Risk Score','SUPPLIER_PORTAL','SUPPLIER_SCORECARDS', 'REJECTION_RATE'),
    ('Supplier Risk Score','SUPPLIER_PORTAL','SUPPLIER_SCORECARDS', 'LEAD_TIME_VARIABILITY'),
    ('Supplier Risk Score','SUPPLIER_PORTAL','SUPPLIER_SCORECARDS', 'SERVICE_SCORE'),
    ('Supplier Risk Score','SAP_ERP',        'PURCHASE_ORDER_LINES','ORDER_QTY'),
    ('Stockout Risk',      'WMS_INVENTORY',  'INVENTORY_SNAPSHOTS', 'AVAILABLE_QTY'),
    ('Stockout Risk',      'WMS_INVENTORY',  'INVENTORY_SNAPSHOTS', 'SAFETY_STOCK_QTY'),
    ('Stockout Risk',      'WMS_INVENTORY',  'INVENTORY_SNAPSHOTS', 'IN_TRANSIT_QTY'),
    ('Stockout Risk',      'DEMAND_PLANNING','DEMAND_HISTORY',      'ACTUAL_DEMAND_QTY'),
    ('Stockout Risk',      'TMS_LOGISTICS',  'SHIPMENTS',           'PROJECTED_DELIVERY_DATE'),
    ('Stockout Risk',      'TMS_LOGISTICS',  'SHIPMENTS',           'EXPECTED_DELIVERY_DATE'),
    ('Stockout Risk',      'SAP_ERP',        'SUPPLIER_MATERIAL',   'CONTRACT_LEAD_TIME_DAYS')
  AS r(METRIC, S, T, C)
),
checked AS (
  SELECT r.METRIC, r.S || '.' || r.T AS TBL, r.C,
         IFF(EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS c
                      WHERE c.TABLE_SCHEMA = r.S AND c.TABLE_NAME = r.T AND c.COLUMN_NAME = r.C),
             1, 0) AS present
  FROM required r
)
SELECT METRIC,
       LISTAGG(DISTINCT TBL, ', ') WITHIN GROUP (ORDER BY TBL)          AS REQUIRED_SOURCE_TABLES,
       COUNT(*)                                                         AS REQUIRED_FIELDS,
       SUM(present)                                                     AS FIELDS_PRESENT,
       LISTAGG(IFF(present = 0, C, NULL), ', ')                         AS MISSING_FIELDS,
       IFF(SUM(present) = COUNT(*), 'YES', 'NO')                        AS READY
FROM checked
GROUP BY METRIC
ORDER BY METRIC;

/* prove the fields are not merely present but populated */
SELECT 'Landed-cost components populated on delivered shipments' AS CHECK_NAME,
       COUNT(*) AS DELIVERED_LINES,
       COUNT_IF(FREIGHT_COST IS NOT NULL AND DUTY_COST IS NOT NULL AND HANDLING_COST IS NOT NULL) AS WITH_COSTS,
       COUNT_IF(OTHER_LOGISTICS_COST IS NULL) AS OPTIONAL_NULL_OTHER_COST
FROM TMS_LOGISTICS.SHIPMENTS
WHERE ACTUAL_DELIVERY_DATE IS NOT NULL;

/* ===========================================================================
   V10 : DATA-QUALITY / CONTROLLED FRAGMENTATION VALIDATION
   =========================================================================== */
SELECT '=== V10 CONTROLLED FRAGMENTATION ===' AS SECTION;

/* same concept, different source-system column names */
SELECT c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME,
       CASE
         WHEN c.COLUMN_NAME IN ('VENDOR_ID','SUPPLIER_CODE','SUPPLIER_ID')                        THEN 'SUPPLIER'
         WHEN c.COLUMN_NAME IN ('MATERIAL_NO','ITEM_CODE','SKU','PART_ID','PART_NUMBER')          THEN 'PART'
         WHEN c.COLUMN_NAME IN ('PLANT_CODE','DESTINATION_SITE','SITE_ID','LOCATION_ID','FULFILLMENT_SITE',
                                'ORIGIN_PLANT','DESTINATION_PLANT')                              THEN 'PLANT'
       END AS CANONICAL_CONCEPT
FROM INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC','CURATED')
  AND c.COLUMN_NAME IN ('VENDOR_ID','SUPPLIER_CODE','SUPPLIER_ID','MATERIAL_NO','ITEM_CODE','SKU',
                        'PART_ID','PART_NUMBER','PLANT_CODE','DESTINATION_SITE','SITE_ID',
                        'LOCATION_ID','FULFILLMENT_SITE','ORIGIN_PLANT','DESTINATION_PLANT')
ORDER BY CANONICAL_CONCEPT, c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME;

/* different date terminology per system */
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE = 'DATE' AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC','CURATED')
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME;

/* supplier display-name formatting drift, canonical ID intact */
SELECT v.VENDOR_ID, v.VENDOR_NAME AS ERP_VENDOR_NAME, p.SUPPLIER_NAME AS PORTAL_SUPPLIER_NAME,
       IFF(v.VENDOR_NAME <> p.SUPPLIER_NAME, 'FORMATTING DIFFERS', 'IDENTICAL') AS DISPLAY_NAME_DRIFT
FROM SAP_ERP.VENDOR_MASTER v
JOIN SUPPLIER_PORTAL.SUPPLIER_PROFILE p ON p.SUPPLIER_ID = v.VENDOR_ID
WHERE v.VENDOR_NAME <> p.SUPPLIER_NAME
ORDER BY v.VENDOR_ID
LIMIT 15;

SELECT 'Suppliers with display-name formatting drift' AS MEASURE,
       COUNT_IF(v.VENDOR_NAME <> p.SUPPLIER_NAME) AS N_DRIFT,
       COUNT(*) AS N_TOTAL,
       'canonical SUPPLIER_ID joins 1:1 regardless of name formatting' AS NOTE
FROM SAP_ERP.VENDOR_MASTER v
JOIN SUPPLIER_PORTAL.SUPPLIER_PROFILE p ON p.SUPPLIER_ID = v.VENDOR_ID;

/* optional NULLs (intentional, non-key fields only) */
SELECT 'SAP_ERP.PURCHASE_ORDER_LINES.CONFIRMATION_DATE' AS OPTIONAL_FIELD,
       COUNT_IF(CONFIRMATION_DATE IS NULL) AS NULLS, COUNT(*) AS ROW_CNT,
       ROUND(100.0 * COUNT_IF(CONFIRMATION_DATE IS NULL) / COUNT(*), 2) AS NULL_PCT
FROM SAP_ERP.PURCHASE_ORDER_LINES
UNION ALL
SELECT 'TMS_LOGISTICS.SHIPMENTS.ACTUAL_DELIVERY_DATE (open lines)',
       COUNT_IF(ACTUAL_DELIVERY_DATE IS NULL), COUNT(*),
       ROUND(100.0 * COUNT_IF(ACTUAL_DELIVERY_DATE IS NULL) / COUNT(*), 2)
FROM TMS_LOGISTICS.SHIPMENTS
UNION ALL
SELECT 'TMS_LOGISTICS.SHIPMENTS.OTHER_LOGISTICS_COST',
       COUNT_IF(OTHER_LOGISTICS_COST IS NULL), COUNT(*),
       ROUND(100.0 * COUNT_IF(OTHER_LOGISTICS_COST IS NULL) / COUNT(*), 2)
FROM TMS_LOGISTICS.SHIPMENTS
UNION ALL
SELECT 'DOCUMENTS.SUPPLIER_DOCUMENTS.SUPPLIER_ID (company-wide policies)',
       COUNT_IF(SUPPLIER_ID IS NULL), COUNT(*),
       ROUND(100.0 * COUNT_IF(SUPPLIER_ID IS NULL) / COUNT(*), 2)
FROM DOCUMENTS.SUPPLIER_DOCUMENTS;

/* no NULLs and no corruption in canonical keys */
SELECT 'Canonical key NULLs / malformed IDs' AS CHECK_NAME, SUM(bad) AS VIOLATIONS,
       IFF(SUM(bad) = 0, 'PASS', 'FAIL') AS RESULT
FROM (
  SELECT COUNT_IF(VENDOR_ID IS NULL OR NOT REGEXP_LIKE(VENDOR_ID, '^S[0-9]{3}$')) AS bad FROM SAP_ERP.VENDOR_MASTER
  UNION ALL SELECT COUNT_IF(MATERIAL_NO IS NULL OR NOT REGEXP_LIKE(MATERIAL_NO, '^P[0-9]{3,4}$')) FROM SAP_ERP.MATERIAL_MASTER
  UNION ALL SELECT COUNT_IF(PLANT_CODE IS NULL OR NOT REGEXP_LIKE(PLANT_CODE, '^P[0-9]{2}$')) FROM SAP_ERP.PLANT_MASTER
  UNION ALL SELECT COUNT_IF(CUSTOMER_ID IS NULL OR NOT REGEXP_LIKE(CUSTOMER_ID, '^C[0-9]{4}$')) FROM CRM_ORDERS.CUSTOMER_MASTER
  UNION ALL SELECT COUNT_IF(CARRIER_CODE IS NULL OR NOT REGEXP_LIKE(CARRIER_CODE, '^CR[0-9]{2}$')) FROM TMS_LOGISTICS.CARRIER_MASTER
  UNION ALL SELECT COUNT_IF(PO_NUMBER IS NULL OR NOT REGEXP_LIKE(PO_NUMBER, '^PO[0-9]{6}$')) FROM SAP_ERP.PURCHASE_ORDER_LINES
  UNION ALL SELECT COUNT_IF(SHIPMENT_ID IS NULL OR NOT REGEXP_LIKE(SHIPMENT_ID, '^SH[0-9]{6}$')) FROM TMS_LOGISTICS.SHIPMENTS
  UNION ALL SELECT COUNT_IF(ORDER_ID IS NULL OR NOT REGEXP_LIKE(ORDER_ID, '^CO[0-9]{6}$')) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES
  UNION ALL SELECT COUNT_IF(DOCUMENT_ID IS NULL OR NOT REGEXP_LIKE(DOCUMENT_ID, '^DOC[0-9]{6}$')) FROM DOCUMENTS.SUPPLIER_DOCUMENTS
);

/* date-logic sanity */
SELECT 'Invalid date relationships' AS CHECK_NAME, SUM(bad) AS VIOLATIONS,
       IFF(SUM(bad) = 0, 'PASS', 'FAIL') AS RESULT
FROM (
  SELECT COUNT_IF(PROMISED_DATE < ORDER_DATE) AS bad FROM SAP_ERP.PURCHASE_ORDER_LINES
  UNION ALL SELECT COUNT_IF(CONFIRMATION_DATE IS NOT NULL AND CONFIRMATION_DATE < ORDER_DATE) FROM SAP_ERP.PURCHASE_ORDER_LINES
  UNION ALL SELECT COUNT_IF(EXPECTED_DELIVERY_DATE < SHIP_DATE) FROM TMS_LOGISTICS.SHIPMENTS
  UNION ALL SELECT COUNT_IF(ACTUAL_DELIVERY_DATE IS NOT NULL AND ACTUAL_DELIVERY_DATE < SHIP_DATE) FROM TMS_LOGISTICS.SHIPMENTS
  UNION ALL SELECT COUNT_IF(DUE_DATE < ORDER_DATE) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES
  UNION ALL SELECT COUNT_IF(RECEIVED_QTY > SHIPPED_QTY) FROM TMS_LOGISTICS.SHIPMENTS
  UNION ALL SELECT COUNT_IF(FULFILLED_QTY > ORDERED_QTY) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES
  UNION ALL SELECT COUNT_IF(AVAILABLE_QTY > ON_HAND_QTY) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS
  UNION ALL SELECT COUNT_IF(EXPIRY_DATE < EFFECTIVE_DATE) FROM DOCUMENTS.SUPPLIER_DOCUMENTS
);

/* worked fragmentation example: one PO line seen through three systems */
SELECT 'ERP'      AS SOURCE_SYSTEM, p.VENDOR_ID AS SUPPLIER, p.MATERIAL_NO AS PART, p.PLANT_CODE AS SITE,
       p.PROMISED_DATE::VARCHAR AS KEY_DATE, p.ORDER_QTY AS QTY
FROM SAP_ERP.PURCHASE_ORDER_LINES p WHERE p.PO_NUMBER = 'PO900001'
UNION ALL
SELECT 'TMS', s.SUPPLIER_CODE, s.ITEM_CODE, s.DESTINATION_SITE,
       s.PROJECTED_DELIVERY_DATE::VARCHAR, s.SHIPPED_QTY
FROM TMS_LOGISTICS.SHIPMENTS s WHERE s.PO_REF = 'PO900001'
UNION ALL
SELECT 'WMS', NULL, i.SKU, i.SITE_ID, i.SNAPSHOT_DATE::VARCHAR, i.AVAILABLE_QTY
FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
CROSS JOIN PUBLIC.DATASET_METADATA m
WHERE m.VERSION = 1 AND i.SKU = 'P104' AND i.SITE_ID = 'P01' AND i.SNAPSHOT_DATE = m.DATASET_ANCHOR_DATE
UNION ALL
SELECT 'PLANNING', NULL, d.PART_ID, d.LOCATION_ID, MAX(d.DEMAND_DATE)::VARCHAR, ROUND(AVG(d.ACTUAL_DEMAND_QTY), 2)
FROM DEMAND_PLANNING.DEMAND_HISTORY d
CROSS JOIN PUBLIC.DATASET_METADATA m
WHERE m.VERSION = 1 AND d.PART_ID = 'P104' AND d.LOCATION_ID = 'P01'
  AND d.DEMAND_DATE BETWEEN DATEADD(day,-30,m.DATASET_ANCHOR_DATE) AND DATEADD(day,-1,m.DATASET_ANCHOR_DATE)
GROUP BY d.PART_ID, d.LOCATION_ID
UNION ALL
SELECT 'CRM', c.CUSTOMER_ID, c.PART_NUMBER, c.FULFILLMENT_SITE, c.DUE_DATE::VARCHAR, c.ORDERED_QTY
FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c WHERE c.ORDER_ID IN ('CO090001','CO090002','CO090003');

/* ===========================================================================
   V11 : SECONDARY DELIBERATE SCENARIOS (the flagship is not the only signal)
   =========================================================================== */
SELECT '=== V11 SECONDARY SCENARIOS ===' AS SECTION;

/* named supplier performance profiles from the latest scorecard */
SELECT sc.SUPPLIER_ID, v.VENDOR_NAME, v.VENDOR_TIER,
       sc.QUALITY_SCORE, sc.REJECTION_RATE, sc.REPORTED_LEAD_TIME_DAYS,
       sc.LEAD_TIME_VARIABILITY, sc.SERVICE_SCORE, sc.RISK_CATEGORY, sc.OPEN_ISSUE_COUNT,
       CASE sc.SUPPLIER_ID
         WHEN 'S011' THEN '1. High-performing supplier'
         WHEN 'S088' THEN '2. Repeatedly poor delivery'
         WHEN 'S073' THEN '10. Poor quality, acceptable delivery'
         WHEN 'S055' THEN '15. Deteriorating over time'
         WHEN 'S017' THEN 'Flagship risk supplier'
         WHEN 'S042' THEN '8. Expensive but reliable alternate'
       END AS SCENARIO
FROM (SELECT * FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS
      QUALIFY ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID ORDER BY SCORECARD_DATE DESC) = 1) sc
JOIN SAP_ERP.VENDOR_MASTER v ON v.VENDOR_ID = sc.SUPPLIER_ID
WHERE sc.SUPPLIER_ID IN ('S011','S017','S042','S055','S073','S088')
ORDER BY sc.SUPPLIER_ID;

/* deterioration trend for S055 (first vs latest scorecard) */
SELECT SUPPLIER_ID,
       MIN_BY(QUALITY_SCORE, SCORECARD_DATE)  AS OLDEST_QUALITY,
       MAX_BY(QUALITY_SCORE, SCORECARD_DATE)  AS LATEST_QUALITY,
       MIN_BY(SERVICE_SCORE, SCORECARD_DATE)  AS OLDEST_SERVICE,
       MAX_BY(SERVICE_SCORE, SCORECARD_DATE)  AS LATEST_SERVICE,
       MIN_BY(REJECTION_RATE, SCORECARD_DATE) AS OLDEST_REJECTION,
       MAX_BY(REJECTION_RATE, SCORECARD_DATE) AS LATEST_REJECTION,
       /* materiality threshold: ignore small month-to-month scorecard noise */
       ROUND(MAX_BY(SERVICE_SCORE, SCORECARD_DATE) - MIN_BY(SERVICE_SCORE, SCORECARD_DATE), 2) AS SERVICE_DELTA,
       CASE WHEN MAX_BY(SERVICE_SCORE, SCORECARD_DATE) - MIN_BY(SERVICE_SCORE, SCORECARD_DATE) <= -10
              THEN 'DETERIORATING'
            WHEN MAX_BY(SERVICE_SCORE, SCORECARD_DATE) - MIN_BY(SERVICE_SCORE, SCORECARD_DATE) >= 10
              THEN 'IMPROVING'
            ELSE 'STABLE' END AS TREND
FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS
WHERE SUPPLIER_ID IN ('S055','S011','S017','S042')
GROUP BY SUPPLIER_ID ORDER BY SUPPLIER_ID;

/* inventory extremes at the latest snapshot */
SELECT 'Excess inventory positions'   AS SCENARIO, COUNT(*) AS N FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
  JOIN PUBLIC.DATASET_METADATA m ON m.VERSION=1 AND i.SNAPSHOT_DATE=m.DATASET_ANCHOR_DATE
  WHERE i.INVENTORY_STATUS = 'EXCESS'
UNION ALL SELECT 'Stockout positions', COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
  JOIN PUBLIC.DATASET_METADATA m ON m.VERSION=1 AND i.SNAPSHOT_DATE=m.DATASET_ANCHOR_DATE
  WHERE i.INVENTORY_STATUS = 'STOCKOUT'
UNION ALL SELECT 'Below safety stock', COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i
  JOIN PUBLIC.DATASET_METADATA m ON m.VERSION=1 AND i.SNAPSHOT_DATE=m.DATASET_ANCHOR_DATE
  WHERE i.INVENTORY_STATUS = 'BELOW_SAFETY'
UNION ALL SELECT 'Partially fulfilled customer order lines', COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES
  WHERE FULFILLED_QTY > 0 AND FULFILLED_QTY < ORDERED_QTY
UNION ALL SELECT 'Cancelled PO lines (excluded from OTD)', COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES
  WHERE PO_STATUS = 'CANCELLED'
UNION ALL SELECT 'PO lines fulfilled by multiple shipments', (SELECT COUNT(*) FROM
  (SELECT PO_REF, PO_LINE_REF FROM TMS_LOGISTICS.SHIPMENTS GROUP BY 1,2 HAVING COUNT(*) > 1))
UNION ALL SELECT 'Shipments delivered early', COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS
  WHERE ACTUAL_DELIVERY_DATE < EXPECTED_DELIVERY_DATE
UNION ALL SELECT 'Shipments currently in transit', COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS
  WHERE SHIPMENT_STATUS = 'IN_TRANSIT'
UNION ALL SELECT 'Volatile-demand part-locations', (SELECT COUNT(DISTINCT PART_ID || '|' || LOCATION_ID)
  FROM DEMAND_PLANNING.DEMAND_HISTORY WHERE DEMAND_PATTERN = 'Volatile');

/* strategic customers with the largest open revenue exposure */
SELECT cm.CUSTOMER_ID, cm.CUSTOMER_NAME, cm.CUSTOMER_SEGMENT, cm.PRIORITY_TIER,
       COUNT(*) AS OPEN_LINES, SUM(c.ORDER_VALUE) AS OPEN_EXPOSURE_INR
FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c
JOIN CRM_ORDERS.CUSTOMER_MASTER cm ON cm.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.ORDER_STATUS IN ('OPEN','PARTIALLY_FULFILLED','OVERDUE')
  AND cm.CUSTOMER_SEGMENT IN ('Strategic','Enterprise')
GROUP BY 1,2,3,4
ORDER BY OPEN_EXPOSURE_INR DESC
LIMIT 10;

/* plant with high inventory cover but weak demand (latest snapshot vs 30-day demand) */
WITH a AS (SELECT DATASET_ANCHOR_DATE AS A FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1),
d AS (
  SELECT LOCATION_ID, SUM(ACTUAL_DEMAND_QTY) / 30.0 AS AVG_DAILY_DEMAND
  FROM DEMAND_PLANNING.DEMAND_HISTORY, a
  WHERE DEMAND_DATE BETWEEN DATEADD(day,-30,a.A) AND DATEADD(day,-1,a.A)
  GROUP BY 1
),
i AS (
  SELECT SITE_ID, SUM(AVAILABLE_QTY) AS AVAILABLE_QTY
  FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS, a
  WHERE SNAPSHOT_DATE = a.A GROUP BY 1
)
SELECT i.SITE_ID AS PLANT, i.AVAILABLE_QTY, ROUND(d.AVG_DAILY_DEMAND, 2) AS AVG_DAILY_DEMAND,
       ROUND(i.AVAILABLE_QTY / NULLIF(d.AVG_DAILY_DEMAND, 0), 1) AS DAYS_OF_COVER
FROM i JOIN d ON d.LOCATION_ID = i.SITE_ID
ORDER BY DAYS_OF_COVER DESC;

/* ===========================================================================
   V12 : OVERALL VALIDATION GATE
   =========================================================================== */
SELECT '=== V12 OVERALL GATE ===' AS SECTION;

WITH a AS (SELECT DATASET_ANCHOR_DATE AS A FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1),
chk AS (
  SELECT 'Row-count targets met' AS CHECK_NAME,
         IFF((SELECT COUNT(*) FROM SAP_ERP.VENDOR_MASTER)            >= 100
         AND (SELECT COUNT(*) FROM SAP_ERP.MATERIAL_MASTER)          >= 1000
         AND (SELECT COUNT(*) FROM SAP_ERP.PLANT_MASTER)             >= 12
         AND (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_MASTER)       >= 500
         AND (SELECT COUNT(*) FROM TMS_LOGISTICS.CARRIER_MASTER)     >= 20
         AND (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES)     >= 50000
         AND (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS)          >= 50000
         AND (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS)>= 100000
         AND (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY)   >= 100000
         AND (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES)  >= 50000
         AND (SELECT COUNT(*) FROM DOCUMENTS.SUPPLIER_DOCUMENTS)     >= 100,
         'PASS','FAIL') AS RESULT
  UNION ALL
  SELECT 'Zero canonical business-key orphans',
         IFF((SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS s
               WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.PURCHASE_ORDER_LINES p
                                  WHERE p.PO_NUMBER = s.PO_REF AND p.PO_LINE_NUMBER = s.PO_LINE_REF)) = 0
         AND (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c
               WHERE NOT EXISTS (SELECT 1 FROM CRM_ORDERS.CUSTOMER_MASTER cm WHERE cm.CUSTOMER_ID = c.CUSTOMER_ID)) = 0
         AND (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY d
               WHERE NOT EXISTS (SELECT 1 FROM SAP_ERP.MATERIAL_MASTER m WHERE m.MATERIAL_NO = d.PART_ID)) = 0,
         'PASS','FAIL')
  UNION ALL
  SELECT 'Flagship inventory 8200 / safety 3000',
         IFF((SELECT AVAILABLE_QTY FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i, a
               WHERE i.SKU='P104' AND i.SITE_ID='P01' AND i.SNAPSHOT_DATE=a.A) = 8200
         AND (SELECT SAFETY_STOCK_QTY FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i, a
               WHERE i.SKU='P104' AND i.SITE_ID='P01' AND i.SNAPSHOT_DATE=a.A) = 3000, 'PASS','FAIL')
  UNION ALL
  SELECT 'Flagship 3 orders / 7350 units / INR 4.2M',
         IFF((SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c, a
               WHERE c.PART_NUMBER='P104' AND c.FULFILLMENT_SITE='P01' AND c.ORDER_STATUS='OPEN'
                 AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A)) = 3
         AND (SELECT SUM(ORDERED_QTY) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c, a
               WHERE c.PART_NUMBER='P104' AND c.FULFILLMENT_SITE='P01' AND c.ORDER_STATUS='OPEN'
                 AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A)) = 7350
         AND (SELECT SUM(ORDER_VALUE) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES c, a
               WHERE c.PART_NUMBER='P104' AND c.FULFILLMENT_SITE='P01' AND c.ORDER_STATUS='OPEN'
                 AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A)) = 4200000, 'PASS','FAIL')
  UNION ALL
  SELECT 'Flagship shipment delay = 5 days',
         IFF((SELECT MAX(DATEDIFF(day, EXPECTED_DELIVERY_DATE, PROJECTED_DELIVERY_DATE))
               FROM TMS_LOGISTICS.SHIPMENTS
              WHERE SUPPLIER_CODE='S017' AND ITEM_CODE='P104' AND DESTINATION_SITE='P01'
                AND ACTUAL_DELIVERY_DATE IS NULL) = 5, 'PASS','FAIL')
  UNION ALL
  SELECT 'Recent avg daily demand P104/P01 ~700',
         IFF((SELECT AVG(ACTUAL_DEMAND_QTY) FROM DEMAND_PLANNING.DEMAND_HISTORY d, a
               WHERE d.PART_ID='P104' AND d.LOCATION_ID='P01'
                 AND d.DEMAND_DATE BETWEEN DATEADD(day,-30,a.A) AND DATEADD(day,-1,a.A))
             BETWEEN 660 AND 740, 'PASS','FAIL')
  UNION ALL
  SELECT 'Expedite option available and faster + costlier',
         IFF(EXISTS (SELECT 1 FROM TMS_LOGISTICS.TRANSPORT_OPTIONS t
                     JOIN SAP_ERP.VENDOR_MASTER v ON v.VENDOR_ID='S017' AND v.REGION=t.ORIGIN_REGION
                     WHERE t.DESTINATION_PLANT='P01' AND t.ACTIVE_FLAG
                       AND t.EXPEDITED_TRANSIT_DAYS < t.NORMAL_TRANSIT_DAYS
                       AND t.EXPEDITE_COST_FACTOR > t.NORMAL_COST_FACTOR
                       AND t.EXPEDITED_TRANSIT_DAYS < 12), 'PASS','FAIL')
  UNION ALL
  SELECT 'P03 can safely transfer >= 2150 units',
         IFF((SELECT LEAST(i.AVAILABLE_QTY - i.SAFETY_STOCK_QTY, o.MAX_TRANSFER_QTY)
                FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS i, TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS o, a
               WHERE i.SKU='P104' AND i.SITE_ID='P03' AND i.SNAPSHOT_DATE=a.A
                 AND o.ORIGIN_PLANT='P03' AND o.DESTINATION_PLANT='P01' AND o.ACTIVE_FLAG) >= 2150,
         'PASS','FAIL')
  UNION ALL
  SELECT 'S042 approved for P104 with capacity >= 2150 and lead time <= 7d',
         IFF(EXISTS (SELECT 1 FROM SAP_ERP.SUPPLIER_MATERIAL sm
                     JOIN SAP_ERP.VENDOR_MASTER v ON v.VENDOR_ID = sm.VENDOR_ID
                     WHERE sm.VENDOR_ID='S042' AND sm.MATERIAL_NO='P104'
                       AND sm.MAX_WEEKLY_SUPPLY_QTY >= 2150
                       AND sm.CONTRACT_LEAD_TIME_DAYS <= 7
                       AND v.VENDOR_STATUS = 'Active'), 'PASS','FAIL')
  UNION ALL
  SELECT 'S042 priced above S017 for P104',
         IFF((SELECT AGREED_UNIT_PRICE FROM SAP_ERP.SUPPLIER_MATERIAL WHERE VENDOR_ID='S042' AND MATERIAL_NO='P104')
           > (SELECT AGREED_UNIT_PRICE FROM SAP_ERP.SUPPLIER_MATERIAL WHERE VENDOR_ID='S017' AND MATERIAL_NO='P104'),
           'PASS','FAIL')
  UNION ALL
  SELECT 'Active S017 SLA / contract available for retrieval',
         IFF(EXISTS (SELECT 1 FROM DOCUMENTS.SUPPLIER_DOCUMENTS d, a
                     WHERE d.SUPPLIER_ID='S017' AND d.DOCUMENT_TYPE IN ('SLA','Supplier Contract')
                       AND d.EXPIRY_DATE >= a.A AND LENGTH(d.CONTENT) > 500), 'PASS','FAIL')
  UNION ALL
  SELECT 'CURATED still empty',
         IFF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='CURATED') = 0, 'PASS','FAIL')
)
SELECT CHECK_NAME, RESULT FROM chk
UNION ALL
SELECT '>>> OVERALL', IFF(COUNT_IF(RESULT = 'FAIL') = 0, 'ALL CHECKS PASS', 'FAILURES PRESENT') FROM chk
ORDER BY IFF(CHECK_NAME LIKE '>>>%', 1, 0), CHECK_NAME;

SELECT 'Phase 1 / 04_data_validation.sql complete' AS STATUS;
