/* ============================================================================
   SupplyChainIQ - Governed Agentic Supply Chain Control Tower
   PHASE 2B : CURATED MODEL VALIDATION
   FILE    : 06_curated_validation.sql
   PURPOSE : Validate the canonical CURATED layer created in
             05_curated_model.sql: object count, grain preservation, key
             uniqueness, referential integrity, supplier harmonization,
             currency preservation, Phase 1 regression, and reproduction of
             the flagship S017 / P104 / P01 scenario via CURATED objects.

   SAFETY  : Read-only. No DDL/DML against any Phase 1 source object.
   ============================================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SUPPLYCHAINIQ_DB;

/* ===========================================================================
   CHECK 1 : Exactly 14 expected CURATED views exist, no unexpected objects
   =========================================================================== */
WITH expected AS (
  SELECT * FROM (VALUES
    ('SUPPLIER'),('PART'),('PLANT'),('SUPPLIER_PART'),('PURCHASE_ORDER_LINE'),
    ('SHIPMENT'),('INVENTORY_SNAPSHOT'),('DEMAND'),('CUSTOMER'),
    ('CUSTOMER_ORDER_LINE'),('CARRIER'),('SUPPLIER_PERFORMANCE'),
    ('TRANSPORT_OPTION'),('INTERPLANT_TRANSFER_OPTION')
  ) AS t(VIEW_NAME)
),
actual AS (
  SELECT TABLE_NAME AS VIEW_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'CURATED'
)
SELECT '1. Exactly 14 expected CURATED views, no extras/missing' AS CHECK_NAME,
       IFF(
         (SELECT COUNT(*) FROM actual) = 14
         AND (SELECT COUNT(*) FROM expected e WHERE NOT EXISTS (SELECT 1 FROM actual a WHERE a.VIEW_NAME = e.VIEW_NAME)) = 0
         AND (SELECT COUNT(*) FROM actual a WHERE NOT EXISTS (SELECT 1 FROM expected e WHERE e.VIEW_NAME = a.VIEW_NAME)) = 0,
         'PASS','FAIL') AS RESULT;

/* ===========================================================================
   CHECK 2 : Canonical master row counts
   =========================================================================== */
SELECT '2a. CURATED.SUPPLIER = 100' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER) = 100, 'PASS','FAIL') AS RESULT
UNION ALL
SELECT '2b. CURATED.PART = 1000',
       IFF((SELECT COUNT(*) FROM CURATED.PART) = 1000, 'PASS','FAIL')
UNION ALL
SELECT '2c. CURATED.PLANT = 12',
       IFF((SELECT COUNT(*) FROM CURATED.PLANT) = 12, 'PASS','FAIL')
UNION ALL
SELECT '2d. CURATED.CUSTOMER = 500',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER) = 500, 'PASS','FAIL')
UNION ALL
SELECT '2e. CURATED.CARRIER = 20',
       IFF((SELECT COUNT(*) FROM CURATED.CARRIER) = 20, 'PASS','FAIL');

/* ===========================================================================
   CHECK 3 : Canonical-key uniqueness
   =========================================================================== */
SELECT '3a. SUPPLIER.SUPPLIER_ID unique' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER) = (SELECT COUNT(DISTINCT SUPPLIER_ID) FROM CURATED.SUPPLIER), 'PASS','FAIL') AS RESULT
UNION ALL
SELECT '3b. PART.PART_ID unique',
       IFF((SELECT COUNT(*) FROM CURATED.PART) = (SELECT COUNT(DISTINCT PART_ID) FROM CURATED.PART), 'PASS','FAIL')
UNION ALL
SELECT '3c. PLANT.PLANT_ID unique',
       IFF((SELECT COUNT(*) FROM CURATED.PLANT) = (SELECT COUNT(DISTINCT PLANT_ID) FROM CURATED.PLANT), 'PASS','FAIL')
UNION ALL
SELECT '3d. CUSTOMER.CUSTOMER_ID unique',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER) = (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM CURATED.CUSTOMER), 'PASS','FAIL')
UNION ALL
SELECT '3e. CARRIER.CARRIER_ID unique',
       IFF((SELECT COUNT(*) FROM CURATED.CARRIER) = (SELECT COUNT(DISTINCT CARRIER_ID) FROM CURATED.CARRIER), 'PASS','FAIL')
UNION ALL
SELECT '3f. SUPPLIER_PART (SUPPLIER_ID,PART_ID) unique',
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PART) = (SELECT COUNT(*) FROM (SELECT DISTINCT SUPPLIER_ID, PART_ID FROM CURATED.SUPPLIER_PART)), 'PASS','FAIL')
UNION ALL
SELECT '3g. PURCHASE_ORDER_LINE (PO_NUMBER,PO_LINE_NUMBER) unique',
       IFF((SELECT COUNT(*) FROM CURATED.PURCHASE_ORDER_LINE) = (SELECT COUNT(*) FROM (SELECT DISTINCT PO_NUMBER, PO_LINE_NUMBER FROM CURATED.PURCHASE_ORDER_LINE)), 'PASS','FAIL')
UNION ALL
SELECT '3h. SHIPMENT (SHIPMENT_ID,SHIPMENT_LINE_NUMBER) unique',
       IFF((SELECT COUNT(*) FROM CURATED.SHIPMENT) = (SELECT COUNT(*) FROM (SELECT DISTINCT SHIPMENT_ID, SHIPMENT_LINE_NUMBER FROM CURATED.SHIPMENT)), 'PASS','FAIL')
UNION ALL
SELECT '3i. INVENTORY_SNAPSHOT (PART_ID,PLANT_ID,SNAPSHOT_DATE) unique',
       IFF((SELECT COUNT(*) FROM CURATED.INVENTORY_SNAPSHOT) = (SELECT COUNT(*) FROM (SELECT DISTINCT PART_ID, PLANT_ID, SNAPSHOT_DATE FROM CURATED.INVENTORY_SNAPSHOT)), 'PASS','FAIL')
UNION ALL
SELECT '3j. DEMAND (PART_ID,PLANT_ID,DEMAND_DATE) unique',
       IFF((SELECT COUNT(*) FROM CURATED.DEMAND) = (SELECT COUNT(*) FROM (SELECT DISTINCT PART_ID, PLANT_ID, DEMAND_DATE FROM CURATED.DEMAND)), 'PASS','FAIL')
UNION ALL
SELECT '3k. CUSTOMER_ORDER_LINE (ORDER_ID,ORDER_LINE) unique',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER_ORDER_LINE) = (SELECT COUNT(*) FROM (SELECT DISTINCT ORDER_ID, ORDER_LINE FROM CURATED.CUSTOMER_ORDER_LINE)), 'PASS','FAIL')
UNION ALL
SELECT '3l. SUPPLIER_PERFORMANCE (SUPPLIER_ID,SCORECARD_DATE) unique',
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PERFORMANCE) = (SELECT COUNT(*) FROM (SELECT DISTINCT SUPPLIER_ID, SCORECARD_DATE FROM CURATED.SUPPLIER_PERFORMANCE)), 'PASS','FAIL')
UNION ALL
SELECT '3m. TRANSPORT_OPTION (ORIGIN_REGION,DESTINATION_PLANT_ID,TRANSPORT_MODE) unique',
       IFF((SELECT COUNT(*) FROM CURATED.TRANSPORT_OPTION) = (SELECT COUNT(*) FROM (SELECT DISTINCT ORIGIN_REGION, DESTINATION_PLANT_ID, TRANSPORT_MODE FROM CURATED.TRANSPORT_OPTION)), 'PASS','FAIL')
UNION ALL
SELECT '3n. INTERPLANT_TRANSFER_OPTION (ORIGIN_PLANT_ID,DESTINATION_PLANT_ID,TRANSPORT_MODE) unique',
       IFF((SELECT COUNT(*) FROM CURATED.INTERPLANT_TRANSFER_OPTION) = (SELECT COUNT(*) FROM (SELECT DISTINCT ORIGIN_PLANT_ID, DESTINATION_PLANT_ID, TRANSPORT_MODE FROM CURATED.INTERPLANT_TRANSFER_OPTION)), 'PASS','FAIL');

/* ===========================================================================
   CHECK 4 : Row-count preservation between every CURATED view and its source
   =========================================================================== */
SELECT '4a. PART == MATERIAL_MASTER' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM CURATED.PART) = (SELECT COUNT(*) FROM SAP_ERP.MATERIAL_MASTER), 'PASS','FAIL') AS RESULT
UNION ALL
SELECT '4b. PLANT == PLANT_MASTER',
       IFF((SELECT COUNT(*) FROM CURATED.PLANT) = (SELECT COUNT(*) FROM SAP_ERP.PLANT_MASTER), 'PASS','FAIL')
UNION ALL
SELECT '4c. SUPPLIER_PART == SUPPLIER_MATERIAL',
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PART) = (SELECT COUNT(*) FROM SAP_ERP.SUPPLIER_MATERIAL), 'PASS','FAIL')
UNION ALL
SELECT '4d. PURCHASE_ORDER_LINE == PURCHASE_ORDER_LINES',
       IFF((SELECT COUNT(*) FROM CURATED.PURCHASE_ORDER_LINE) = (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES), 'PASS','FAIL')
UNION ALL
SELECT '4e. SHIPMENT == SHIPMENTS',
       IFF((SELECT COUNT(*) FROM CURATED.SHIPMENT) = (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS), 'PASS','FAIL')
UNION ALL
SELECT '4f. INVENTORY_SNAPSHOT == INVENTORY_SNAPSHOTS',
       IFF((SELECT COUNT(*) FROM CURATED.INVENTORY_SNAPSHOT) = (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS), 'PASS','FAIL')
UNION ALL
SELECT '4g. DEMAND == DEMAND_HISTORY',
       IFF((SELECT COUNT(*) FROM CURATED.DEMAND) = (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY), 'PASS','FAIL')
UNION ALL
SELECT '4h. CUSTOMER == CUSTOMER_MASTER',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER) = (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_MASTER), 'PASS','FAIL')
UNION ALL
SELECT '4i. CUSTOMER_ORDER_LINE == CUSTOMER_ORDER_LINES',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER_ORDER_LINE) = (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES), 'PASS','FAIL')
UNION ALL
SELECT '4j. CARRIER == CARRIER_MASTER',
       IFF((SELECT COUNT(*) FROM CURATED.CARRIER) = (SELECT COUNT(*) FROM TMS_LOGISTICS.CARRIER_MASTER), 'PASS','FAIL')
UNION ALL
SELECT '4k. SUPPLIER_PERFORMANCE == SUPPLIER_SCORECARDS',
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PERFORMANCE) = (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS), 'PASS','FAIL')
UNION ALL
SELECT '4l. TRANSPORT_OPTION == TRANSPORT_OPTIONS',
       IFF((SELECT COUNT(*) FROM CURATED.TRANSPORT_OPTION) = (SELECT COUNT(*) FROM TMS_LOGISTICS.TRANSPORT_OPTIONS), 'PASS','FAIL')
UNION ALL
SELECT '4m. INTERPLANT_TRANSFER_OPTION == INTERPLANT_TRANSFER_OPTIONS',
       IFF((SELECT COUNT(*) FROM CURATED.INTERPLANT_TRANSFER_OPTION) = (SELECT COUNT(*) FROM TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS), 'PASS','FAIL');

/* ===========================================================================
   CHECK 5 : CURATED.SUPPLIER remains exactly 100 rows after ERP <-> Portal join
   =========================================================================== */
SELECT '5. CURATED.SUPPLIER == 100 (no fan-out from LEFT JOIN)' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER) = 100
       AND (SELECT COUNT(*) FROM CURATED.SUPPLIER) = (SELECT COUNT(*) FROM SAP_ERP.VENDOR_MASTER),
       'PASS','FAIL') AS RESULT;

/* ===========================================================================
   CHECK 6 : No canonical relationship orphans
   =========================================================================== */
SELECT '6a. Supplier-Part -> Supplier no orphans' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PART sp WHERE NOT EXISTS (SELECT 1 FROM CURATED.SUPPLIER s WHERE s.SUPPLIER_ID = sp.SUPPLIER_ID)) = 0, 'PASS','FAIL') AS RESULT
UNION ALL
SELECT '6b. Supplier-Part -> Part no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PART sp WHERE NOT EXISTS (SELECT 1 FROM CURATED.PART p WHERE p.PART_ID = sp.PART_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6c. PO Line -> Supplier no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.PURCHASE_ORDER_LINE pol WHERE NOT EXISTS (SELECT 1 FROM CURATED.SUPPLIER s WHERE s.SUPPLIER_ID = pol.SUPPLIER_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6d. PO Line -> Part no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.PURCHASE_ORDER_LINE pol WHERE NOT EXISTS (SELECT 1 FROM CURATED.PART p WHERE p.PART_ID = pol.PART_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6e. PO Line -> Plant no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.PURCHASE_ORDER_LINE pol WHERE NOT EXISTS (SELECT 1 FROM CURATED.PLANT pl WHERE pl.PLANT_ID = pol.PLANT_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6f. Inventory Snapshot -> Part no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.INVENTORY_SNAPSHOT i WHERE NOT EXISTS (SELECT 1 FROM CURATED.PART p WHERE p.PART_ID = i.PART_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6g. Inventory Snapshot -> Plant no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.INVENTORY_SNAPSHOT i WHERE NOT EXISTS (SELECT 1 FROM CURATED.PLANT pl WHERE pl.PLANT_ID = i.PLANT_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6h. Demand -> Part no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.DEMAND d WHERE NOT EXISTS (SELECT 1 FROM CURATED.PART p WHERE p.PART_ID = d.PART_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6i. Demand -> Plant no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.DEMAND d WHERE NOT EXISTS (SELECT 1 FROM CURATED.PLANT pl WHERE pl.PLANT_ID = d.PLANT_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6j. Customer Order Line -> Customer no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER_ORDER_LINE c WHERE NOT EXISTS (SELECT 1 FROM CURATED.CUSTOMER cm WHERE cm.CUSTOMER_ID = c.CUSTOMER_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6k. Customer Order Line -> Part no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER_ORDER_LINE c WHERE NOT EXISTS (SELECT 1 FROM CURATED.PART p WHERE p.PART_ID = c.PART_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6l. Customer Order Line -> Plant no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.CUSTOMER_ORDER_LINE c WHERE NOT EXISTS (SELECT 1 FROM CURATED.PLANT pl WHERE pl.PLANT_ID = c.PLANT_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6m. Purchase Order Line <-> Shipment no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.SHIPMENT s
             WHERE NOT EXISTS (SELECT 1 FROM CURATED.PURCHASE_ORDER_LINE p
                               WHERE p.PO_NUMBER = s.PO_NUMBER AND p.PO_LINE_NUMBER = s.PO_LINE_NUMBER)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6n. Shipment -> Carrier no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.SHIPMENT s WHERE NOT EXISTS (SELECT 1 FROM CURATED.CARRIER c WHERE c.CARRIER_ID = s.CARRIER_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6o. Supplier Performance -> Supplier no orphans',
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PERFORMANCE sp WHERE NOT EXISTS (SELECT 1 FROM CURATED.SUPPLIER s WHERE s.SUPPLIER_ID = sp.SUPPLIER_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6p. Transport Option -> Plant no orphans (destination)',
       IFF((SELECT COUNT(*) FROM CURATED.TRANSPORT_OPTION t WHERE NOT EXISTS (SELECT 1 FROM CURATED.PLANT pl WHERE pl.PLANT_ID = t.DESTINATION_PLANT_ID)) = 0, 'PASS','FAIL')
UNION ALL
SELECT '6q. Interplant Transfer Option -> Plant no orphans (origin+destination)',
       IFF((SELECT COUNT(*) FROM CURATED.INTERPLANT_TRANSFER_OPTION i
             WHERE NOT EXISTS (SELECT 1 FROM CURATED.PLANT pl WHERE pl.PLANT_ID = i.ORIGIN_PLANT_ID)
                OR NOT EXISTS (SELECT 1 FROM CURATED.PLANT pl WHERE pl.PLANT_ID = i.DESTINATION_PLANT_ID)) = 0, 'PASS','FAIL');

/* ===========================================================================
   CHECK 7 : Supplier harmonization remains 1:1 by SUPPLIER_ID
   =========================================================================== */
SELECT '7. Supplier harmonization 1:1 (no ERP supplier duplicated by portal join)' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER) = (SELECT COUNT(DISTINCT SUPPLIER_ID) FROM CURATED.SUPPLIER)
       AND (SELECT COUNT(*) FROM CURATED.SUPPLIER WHERE HAS_PORTAL_PROFILE) = 100,
       'PASS','FAIL') AS RESULT;

/* ===========================================================================
   CHECK 8 : Currency columns remain preserved (unconverted) for monetary facts
   =========================================================================== */
SELECT '8a. SUPPLIER_PART.CURRENCY preserved, matches source' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM CURATED.SUPPLIER_PART sp
             JOIN SAP_ERP.SUPPLIER_MATERIAL sm ON sm.VENDOR_ID = sp.SUPPLIER_ID AND sm.MATERIAL_NO = sp.PART_ID
             WHERE sp.CURRENCY IS DISTINCT FROM sm.CURRENCY) = 0, 'PASS','FAIL') AS RESULT
UNION ALL
SELECT '8b. PURCHASE_ORDER_LINE.CURRENCY preserved, matches source',
       IFF((SELECT COUNT(*) FROM CURATED.PURCHASE_ORDER_LINE pol
             JOIN SAP_ERP.PURCHASE_ORDER_LINES p ON p.PO_NUMBER = pol.PO_NUMBER AND p.PO_LINE_NUMBER = pol.PO_LINE_NUMBER
             WHERE pol.CURRENCY IS DISTINCT FROM p.CURRENCY) = 0, 'PASS','FAIL')
UNION ALL
SELECT '8c. No FX conversion applied (SUPPLIER_PART currency has >1 distinct value, unmodified)',
       IFF((SELECT COUNT(DISTINCT CURRENCY) FROM CURATED.SUPPLIER_PART) = (SELECT COUNT(DISTINCT CURRENCY) FROM SAP_ERP.SUPPLIER_MATERIAL), 'PASS','FAIL');

/* ===========================================================================
   CHECK 9 : No unexpected objects exist in CURATED
   =========================================================================== */
SELECT '9. CURATED contains only the 14 expected views (no tables/other objects)' AS CHECK_NAME,
       IFF(
         (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'CURATED' AND TABLE_TYPE = 'BASE TABLE') = 0
         AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'CURATED') = 14,
         'PASS','FAIL') AS RESULT;

/* ===========================================================================
   CHECK 10 : Phase 1 regression - source objects untouched, row counts intact
   =========================================================================== */
SELECT '10a. Phase 1 row counts unchanged' AS CHECK_NAME,
       IFF(
            (SELECT COUNT(*) FROM SAP_ERP.VENDOR_MASTER) = 100
        AND (SELECT COUNT(*) FROM SAP_ERP.MATERIAL_MASTER) = 1000
        AND (SELECT COUNT(*) FROM SAP_ERP.PLANT_MASTER) = 12
        AND (SELECT COUNT(*) FROM SAP_ERP.SUPPLIER_MATERIAL) = 1401
        AND (SELECT COUNT(*) FROM SAP_ERP.PURCHASE_ORDER_LINES) = 54871
        AND (SELECT COUNT(*) FROM TMS_LOGISTICS.CARRIER_MASTER) = 20
        AND (SELECT COUNT(*) FROM TMS_LOGISTICS.SHIPMENTS) = 54024
        AND (SELECT COUNT(*) FROM TMS_LOGISTICS.TRANSPORT_OPTIONS) = 96
        AND (SELECT COUNT(*) FROM TMS_LOGISTICS.INTERPLANT_TRANSFER_OPTIONS) = 42
        AND (SELECT COUNT(*) FROM WMS_INVENTORY.INVENTORY_SNAPSHOTS) = 104000
        AND (SELECT COUNT(*) FROM DEMAND_PLANNING.DEMAND_HISTORY) = 120000
        AND (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_MASTER) = 500
        AND (SELECT COUNT(*) FROM CRM_ORDERS.CUSTOMER_ORDER_LINES) = 52494
        AND (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_PROFILE) = 100
        AND (SELECT COUNT(*) FROM SUPPLIER_PORTAL.SUPPLIER_SCORECARDS) = 1200
        AND (SELECT COUNT(*) FROM DOCUMENTS.SUPPLIER_DOCUMENTS) = 139,
       'PASS','FAIL') AS RESULT;

/* ===========================================================================
   CHECK 11 : Flagship scenario S017 -> P104 -> P01 reproduced via CURATED
   =========================================================================== */
WITH a AS (SELECT DATASET_ANCHOR_DATE AS A FROM PUBLIC.DATASET_METADATA WHERE VERSION = 1),
f AS (
  SELECT
    (SELECT i.AVAILABLE_QTY FROM CURATED.INVENTORY_SNAPSHOT i CROSS JOIN a
      WHERE i.PART_ID='P104' AND i.PLANT_ID='P01' AND i.SNAPSHOT_DATE=a.A)                AS avail,
    (SELECT i.SAFETY_STOCK_QTY FROM CURATED.INVENTORY_SNAPSHOT i CROSS JOIN a
      WHERE i.PART_ID='P104' AND i.PLANT_ID='P01' AND i.SNAPSHOT_DATE=a.A)                AS ss,
    (SELECT COUNT(*) FROM CURATED.CUSTOMER_ORDER_LINE c CROSS JOIN a
      WHERE c.PART_ID='P104' AND c.PLANT_ID='P01' AND c.ORDER_STATUS='OPEN'
        AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A))                               AS n_orders,
    (SELECT SUM(c.ORDERED_QTY) FROM CURATED.CUSTOMER_ORDER_LINE c CROSS JOIN a
      WHERE c.PART_ID='P104' AND c.PLANT_ID='P01' AND c.ORDER_STATUS='OPEN'
        AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A))                               AS req,
    (SELECT SUM(c.ORDER_VALUE) FROM CURATED.CUSTOMER_ORDER_LINE c CROSS JOIN a
      WHERE c.PART_ID='P104' AND c.PLANT_ID='P01' AND c.ORDER_STATUS='OPEN'
        AND c.DUE_DATE BETWEEN a.A AND DATEADD(day,14,a.A))                               AS exposure,
    (SELECT ROUND(AVG(d.ACTUAL_DEMAND_QTY),2) FROM CURATED.DEMAND d CROSS JOIN a
      WHERE d.PART_ID='P104' AND d.PLANT_ID='P01'
        AND d.DEMAND_DATE BETWEEN DATEADD(day,-30,a.A) AND DATEADD(day,-1,a.A))           AS add30,
    (SELECT MAX(DATEDIFF(day, s.EXPECTED_DELIVERY_DATE, s.PROJECTED_DELIVERY_DATE))
       FROM CURATED.SHIPMENT s
      WHERE s.SUPPLIER_ID='S017' AND s.PART_ID='P104' AND s.PLANT_ID='P01'
        AND s.ACTUAL_DELIVERY_DATE IS NULL)                                               AS delay
)
SELECT '11a. AVAILABLE_QTY = 8200' AS ASSERTION, IFF(avail = 8200, 'PASS','FAIL') AS RESULT FROM f
UNION ALL SELECT '11b. SAFETY_STOCK_QTY = 3000',       IFF(ss = 3000, 'PASS','FAIL') FROM f
UNION ALL SELECT '11c. SAFE_USABLE_INVENTORY = 5200',  IFF(avail - ss = 5200, 'PASS','FAIL') FROM f
UNION ALL SELECT '11d. AFFECTED_CUSTOMER_ORDERS = 3',  IFF(n_orders = 3, 'PASS','FAIL') FROM f
UNION ALL SELECT '11e. CUSTOMER_REQUIREMENT = 7350',   IFF(req = 7350, 'PASS','FAIL') FROM f
UNION ALL SELECT '11f. PROJECTED_SHORTAGE = 2150',     IFF(req - (avail - ss) = 2150, 'PASS','FAIL') FROM f
UNION ALL SELECT '11g. REVENUE_EXPOSURE_INR = 4200000',IFF(exposure = 4200000, 'PASS','FAIL') FROM f
UNION ALL SELECT '11h. AVG_DAILY_DEMAND_30D ~700',      IFF(add30 BETWEEN 660 AND 740, 'PASS','FAIL') FROM f
UNION ALL SELECT '11i. SHIPMENT_DELAY_DAYS = 5',        IFF(delay = 5, 'PASS','FAIL') FROM f
UNION ALL
SELECT '11j. Expedite APAC->P01 option available (faster+costlier)',
       IFF(EXISTS (SELECT 1 FROM CURATED.TRANSPORT_OPTION t
                   JOIN CURATED.SUPPLIER v ON v.SUPPLIER_ID='S017' AND v.REGION=t.ORIGIN_REGION
                   WHERE t.DESTINATION_PLANT_ID='P01' AND t.ACTIVE_FLAG
                     AND t.EXPEDITED_TRANSIT_DAYS < t.NORMAL_TRANSIT_DAYS
                     AND t.EXPEDITE_COST_FACTOR > t.NORMAL_COST_FACTOR
                     AND t.EXPEDITED_TRANSIT_DAYS < 12), 'PASS','FAIL')
UNION ALL
SELECT '11k. P03->P01 transfer option capacity >= 2150',
       IFF((SELECT LEAST(i.AVAILABLE_QTY - i.SAFETY_STOCK_QTY, o.MAX_TRANSFER_QTY)
              FROM CURATED.INVENTORY_SNAPSHOT i, CURATED.INTERPLANT_TRANSFER_OPTION o, PUBLIC.DATASET_METADATA md
             WHERE i.PART_ID='P104' AND i.PLANT_ID='P03' AND i.SNAPSHOT_DATE=md.DATASET_ANCHOR_DATE AND md.VERSION=1
               AND o.ORIGIN_PLANT_ID='P03' AND o.DESTINATION_PLANT_ID='P01' AND o.ACTIVE_FLAG) >= 2150,
       'PASS','FAIL')
UNION ALL
SELECT '11l. S042 approved for P104, capacity >=2150, lead time <=7d, active',
       IFF(EXISTS (SELECT 1 FROM CURATED.SUPPLIER_PART sp
                   JOIN CURATED.SUPPLIER v ON v.SUPPLIER_ID = sp.SUPPLIER_ID
                   WHERE sp.SUPPLIER_ID='S042' AND sp.PART_ID='P104'
                     AND sp.MAX_WEEKLY_SUPPLY_QTY >= 2150
                     AND sp.CONTRACT_LEAD_TIME_DAYS <= 7
                     AND v.VENDOR_STATUS = 'Active'), 'PASS','FAIL')
UNION ALL
SELECT '11m. S042 priced above S017 for P104',
       IFF((SELECT AGREED_UNIT_PRICE FROM CURATED.SUPPLIER_PART WHERE SUPPLIER_ID='S042' AND PART_ID='P104')
         > (SELECT AGREED_UNIT_PRICE FROM CURATED.SUPPLIER_PART WHERE SUPPLIER_ID='S017' AND PART_ID='P104'),
       'PASS','FAIL');

/* ===========================================================================
   FINAL SUMMARY : count all checks and roll up
   =========================================================================== */
SELECT 'Phase 2B / 06_curated_validation.sql complete' AS STATUS;
