/* ============================================================================
   SupplyChainIQ - PHASE 10 : PROACTIVE RISK INTELLIGENCE VALIDATION
   FILE    : 25_risk_intelligence_validation.sql
   PURPOSE : Read-only validation of RISK views and recommendation enrichment.
   SAFETY  : SELECT only by default. Manual/live evaluator CALL steps are
             commented and clearly labelled; no approval, review, execution,
             or source-data mutation is performed by this file.
   ============================================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SUPPLYCHAINIQ_DB;

-- V1: Risk candidates are generated and all logical keys are deterministic.
SELECT COUNT(*) AS CANDIDATE_COUNT
FROM RISK.SUPPLY_CHAIN_RISK_CANDIDATES;

SELECT
    COUNT(*) AS RISK_ROWS,
    COUNT(DISTINCT RISK_ID) AS DISTINCT_RISK_IDS,
    COUNT(DISTINCT SUPPLIER_ID || '|' || PART_ID || '|' || PLANT_ID) AS DISTINCT_GRAINS,
    IFF(
        COUNT(*) = COUNT(DISTINCT RISK_ID)
        AND COUNT(*) = COUNT(DISTINCT SUPPLIER_ID || '|' || PART_ID || '|' || PLANT_ID),
        'PASS',
        'FAIL'
    ) AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING;

-- V2: Each RISK_ID follows the deterministic supplier/part/plant strategy.
SELECT
    'RISK_ID_FORMAT' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING
WHERE RISK_ID <> 'RISK::' || SUPPLIER_ID || '::' || PART_ID || '::' || PLANT_ID;

-- V3: Component nulls, component bounds, total-score bounds, and severity thresholds.
SELECT
    'SCORE_COMPONENT_NOT_NULL' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING
WHERE RISK_SCORE IS NULL
   OR SHORTAGE_SCORE IS NULL
   OR URGENCY_SCORE IS NULL
   OR REVENUE_SCORE IS NULL
   OR SHIPMENT_SCORE IS NULL
   OR SUPPLIER_SCORE IS NULL;

SELECT
    'SCORE_BOUNDS_AND_SEVERITY' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING
WHERE SHORTAGE_SCORE NOT BETWEEN 0 AND 45
   OR URGENCY_SCORE NOT BETWEEN 0 AND 20
   OR REVENUE_SCORE NOT BETWEEN 0 AND 15
   OR SHIPMENT_SCORE NOT BETWEEN 0 AND 10
   OR SUPPLIER_SCORE NOT BETWEEN 0 AND 10
   OR RISK_SCORE NOT BETWEEN 0 AND 100
   OR (SEVERITY = 'CRITICAL' AND RISK_SCORE < 70)
   OR (SEVERITY = 'HIGH' AND (RISK_SCORE < 50 OR RISK_SCORE >= 70))
   OR (SEVERITY = 'MEDIUM' AND (RISK_SCORE < 30 OR RISK_SCORE >= 50))
   OR (SEVERITY = 'LOW' AND RISK_SCORE >= 30);

-- V4: Shortage values reconcile exactly to the evaluator-aligned formula.
SELECT
    'SHORTAGE_FORMULA' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING
WHERE SHORTAGE_QUANTITY <> GREATEST(REQUIREMENT_QUANTITY - USABLE_QUANTITY, 0)
   OR USABLE_QUANTITY <> GREATEST(AVAILABLE_QUANTITY - SAFETY_STOCK, 0);

-- V5: Customer exposure is scoped to the same Part x Plant risk grain.
WITH ref AS (
    SELECT DATASET_ANCHOR_DATE AS REFERENCE_DATE
    FROM PUBLIC.DATASET_METADATA
    ORDER BY VERSION DESC
    LIMIT 1
),
expected_open_demand AS (
    SELECT
        c.PART_ID,
        c.PLANT_ID,
        SUM(GREATEST(c.ORDERED_QTY - c.FULFILLED_QTY, 0)) AS EXPECTED_REQUIREMENT_QUANTITY,
        COUNT(*) AS EXPECTED_AFFECTED_ORDER_LINES,
        SUM(c.ORDER_VALUE) AS EXPECTED_REVENUE_EXPOSURE
    FROM CURATED.CUSTOMER_ORDER_LINE c
    CROSS JOIN ref
    WHERE c.ORDER_STATUS NOT IN ('CANCELLED', 'FULFILLED')
      AND c.DUE_DATE BETWEEN ref.REFERENCE_DATE AND DATEADD(day, 14, ref.REFERENCE_DATE)
    GROUP BY c.PART_ID, c.PLANT_ID
)
SELECT
    'CUSTOMER_EXPOSURE_PART_PLANT_RECONCILIATION' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING r
LEFT JOIN expected_open_demand e
  ON e.PART_ID = r.PART_ID
 AND e.PLANT_ID = r.PLANT_ID
WHERE COALESCE(r.REQUIREMENT_QUANTITY, -1) <> COALESCE(e.EXPECTED_REQUIREMENT_QUANTITY, -1)
   OR COALESCE(r.AFFECTED_ORDER_LINES, -1) <> COALESCE(e.EXPECTED_AFFECTED_ORDER_LINES, -1)
   OR COALESCE(r.REVENUE_EXPOSURE, -1) <> COALESCE(e.EXPECTED_REVENUE_EXPOSURE, -1);

-- V6: Source supplier attribution is current, single-row, primary-first, and deterministic.
WITH ref AS (
    SELECT DATASET_ANCHOR_DATE AS REFERENCE_DATE
    FROM PUBLIC.DATASET_METADATA
    ORDER BY VERSION DESC
    LIMIT 1
),
valid_sources AS (
    SELECT
        sp.PART_ID,
        sp.SUPPLIER_ID,
        sp.IS_PRIMARY_SUPPLIER,
        sp.VALID_FROM,
        sp.VALID_TO,
        ROW_NUMBER() OVER (
            PARTITION BY sp.PART_ID
            ORDER BY IFF(sp.IS_PRIMARY_SUPPLIER, 0, 1), sp.SUPPLIER_ID
        ) AS EXPECTED_SOURCE_RN
    FROM CURATED.SUPPLIER_PART sp
    JOIN CURATED.SUPPLIER s
      ON s.SUPPLIER_ID = sp.SUPPLIER_ID
    CROSS JOIN ref
    WHERE s.VENDOR_STATUS = 'Active'
      AND sp.VALID_FROM <= ref.REFERENCE_DATE
      AND sp.VALID_TO >= ref.REFERENCE_DATE
),
expected_source AS (
    SELECT *
    FROM valid_sources
    WHERE EXPECTED_SOURCE_RN = 1
)
SELECT
    'SUPPLIER_ATTRIBUTION_SELECTED_SOURCE' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING r
LEFT JOIN expected_source e
  ON e.PART_ID = r.PART_ID
WHERE r.SUPPLIER_ID <> e.SUPPLIER_ID
   OR e.VALID_FROM > r.REFERENCE_DATE
   OR e.VALID_TO < r.REFERENCE_DATE;

WITH parts_in_risk AS (
    SELECT DISTINCT PART_ID
    FROM RISK.SUPPLY_CHAIN_RISK_RANKING
)
SELECT
    'SUPPLIER_ATTRIBUTION_ONE_SELECTED_SOURCE_PER_PART' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM (
    SELECT PART_ID, COUNT(DISTINCT SUPPLIER_ID) AS SELECTED_SUPPLIER_COUNT
    FROM RISK.SUPPLY_CHAIN_RISK_RANKING
    GROUP BY PART_ID
    HAVING COUNT(DISTINCT SUPPLIER_ID) > 1
) violations;

WITH ref AS (
    SELECT DATASET_ANCHOR_DATE AS REFERENCE_DATE
    FROM PUBLIC.DATASET_METADATA
    ORDER BY VERSION DESC
    LIMIT 1
),
valid_sources AS (
    SELECT
        sp.PART_ID,
        sp.SUPPLIER_ID,
        sp.IS_PRIMARY_SUPPLIER,
        ROW_NUMBER() OVER (
            PARTITION BY sp.PART_ID
            ORDER BY IFF(sp.IS_PRIMARY_SUPPLIER, 0, 1), sp.SUPPLIER_ID
        ) AS EXPECTED_SOURCE_RN
    FROM CURATED.SUPPLIER_PART sp
    JOIN CURATED.SUPPLIER s
      ON s.SUPPLIER_ID = sp.SUPPLIER_ID
    CROSS JOIN ref
    WHERE s.VENDOR_STATUS = 'Active'
      AND sp.VALID_FROM <= ref.REFERENCE_DATE
      AND sp.VALID_TO >= ref.REFERENCE_DATE
),
parts_in_risk AS (
    SELECT DISTINCT PART_ID
    FROM RISK.SUPPLY_CHAIN_RISK_RANKING
)
SELECT
    'SUPPLIER_ATTRIBUTION_PRIMARY_SELECTED_WHEN_PRESENT' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM parts_in_risk p
JOIN valid_sources selected
  ON selected.PART_ID = p.PART_ID
 AND selected.EXPECTED_SOURCE_RN = 1
WHERE EXISTS (
    SELECT 1
    FROM valid_sources primary_source
    WHERE primary_source.PART_ID = p.PART_ID
      AND primary_source.IS_PRIMARY_SUPPLIER = TRUE
)
  AND selected.IS_PRIMARY_SUPPLIER <> TRUE;

WITH ref AS (
    SELECT DATASET_ANCHOR_DATE AS REFERENCE_DATE
    FROM PUBLIC.DATASET_METADATA
    ORDER BY VERSION DESC
    LIMIT 1
),
valid_sources AS (
    SELECT
        sp.PART_ID,
        sp.SUPPLIER_ID,
        sp.IS_PRIMARY_SUPPLIER,
        ROW_NUMBER() OVER (
            PARTITION BY sp.PART_ID
            ORDER BY IFF(sp.IS_PRIMARY_SUPPLIER, 0, 1), sp.SUPPLIER_ID
        ) AS EXPECTED_SOURCE_RN
    FROM CURATED.SUPPLIER_PART sp
    JOIN CURATED.SUPPLIER s
      ON s.SUPPLIER_ID = sp.SUPPLIER_ID
    CROSS JOIN ref
    WHERE s.VENDOR_STATUS = 'Active'
      AND sp.VALID_FROM <= ref.REFERENCE_DATE
      AND sp.VALID_TO >= ref.REFERENCE_DATE
),
expected_sources AS (
    SELECT PART_ID, SUPPLIER_ID
    FROM valid_sources
    WHERE EXPECTED_SOURCE_RN = 1
),
selected_sources AS (
    SELECT DISTINCT PART_ID, SUPPLIER_ID
    FROM RISK.SUPPLY_CHAIN_RISK_RANKING
)
SELECT
    'SUPPLIER_ATTRIBUTION_DETERMINISTIC_TIE_BREAK' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM selected_sources selected
LEFT JOIN expected_sources expected
  ON expected.PART_ID = selected.PART_ID
WHERE expected.SUPPLIER_ID IS NULL
   OR selected.SUPPLIER_ID <> expected.SUPPLIER_ID;

SELECT
    'SUPPLIER_ATTRIBUTION_P104_S017_IF_SUPPORTED' AS CHECK_NAME,
    COUNT(*) AS QUALIFYING_RISK_ROWS,
    IFF(
        COUNT(*) = 0
        OR (
            COUNT(*) = 1
            AND MIN(SUPPLIER_ID) = 'S017'
            AND MIN(PART_ID) = 'P104'
            AND MIN(PLANT_ID) = 'P01'
        ),
        'PASS',
        'FAIL'
    ) AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING
WHERE PART_ID = 'P104'
  AND PLANT_ID = 'P01';

-- V7: Delayed shipment attribution uses only qualifying delayed in-transit shipments.
WITH expected_delayed AS (
    SELECT
        s.SUPPLIER_ID,
        s.PART_ID,
        s.PLANT_ID,
        s.SHIPMENT_ID,
        DATEDIFF(day, p.PROMISED_DATE, s.PROJECTED_DELIVERY_DATE) AS EXPECTED_DELAY_DAYS,
        ROW_NUMBER() OVER (
            PARTITION BY s.SUPPLIER_ID, s.PART_ID, s.PLANT_ID
            ORDER BY s.PROJECTED_DELIVERY_DATE, s.SHIPMENT_ID
        ) AS EXPECTED_SHIPMENT_RN
    FROM CURATED.SHIPMENT s
    JOIN CURATED.PURCHASE_ORDER_LINE p
      ON p.PO_NUMBER = s.PO_NUMBER
     AND p.PO_LINE_NUMBER = s.PO_LINE_NUMBER
    WHERE s.SHIPMENT_STATUS = 'IN_TRANSIT'
      AND s.PROJECTED_DELIVERY_DATE > p.PROMISED_DATE
),
expected_winner AS (
    SELECT *
    FROM expected_delayed
    WHERE EXPECTED_SHIPMENT_RN = 1
)
SELECT
    'DELAYED_SHIPMENT_ATTRIBUTION' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING r
LEFT JOIN expected_winner e
  ON e.SUPPLIER_ID = r.SUPPLIER_ID
 AND e.PART_ID = r.PART_ID
 AND e.PLANT_ID = r.PLANT_ID
WHERE (r.DELAYED_SHIPMENT_ID IS NOT NULL AND r.DELAYED_SHIPMENT_ID <> e.SHIPMENT_ID)
   OR (r.DELAYED_SHIPMENT_ID IS NOT NULL AND r.SHIPMENT_STATUS <> 'IN_TRANSIT')
   OR (r.DELAYED_SHIPMENT_ID IS NOT NULL AND r.DELAY_DAYS <> e.EXPECTED_DELAY_DAYS)
   OR (r.DELAYED_SHIPMENT_ID IS NULL AND e.SHIPMENT_ID IS NOT NULL);

SELECT
    'DELAYED_SHIPMENT_ONE_SELECTED_PER_RISK' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM (
    SELECT RISK_ID, COUNT(DISTINCT DELAYED_SHIPMENT_ID) AS SELECTED_SHIPMENTS
    FROM RISK.SUPPLY_CHAIN_RISK_RANKING
    WHERE DELAYED_SHIPMENT_ID IS NOT NULL
    GROUP BY RISK_ID
    HAVING COUNT(DISTINCT DELAYED_SHIPMENT_ID) > 1
) violations;

-- V8: Ranking is deterministic: score descending, then RISK_ID ascending.
SELECT RISK_RANK, RISK_ID, RISK_SCORE, SEVERITY, PRIMARY_RISK_REASON
FROM RISK.SUPPLY_CHAIN_RISK_RANKING
ORDER BY RISK_RANK, RISK_ID;

SELECT
    'TOP_RANK_HAS_HIGHEST_SCORE' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING r
WHERE r.RISK_RANK = 1
  AND r.RISK_SCORE < (SELECT MAX(RISK_SCORE) FROM RISK.SUPPLY_CHAIN_RISK_RANKING);

SELECT
    'RANKING_ROW_NUMBER_RECOMPUTE' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM (
    SELECT
        RISK_ID,
        RISK_RANK,
        ROW_NUMBER() OVER (ORDER BY RISK_SCORE DESC, RISK_ID) AS RECOMPUTED_RANK
    FROM RISK.SUPPLY_CHAIN_RISK_RANKING
)
recomputed
WHERE RISK_RANK <> RECOMPUTED_RANK;

SELECT
    'RANKING_TIE_BREAK_RISK_ID_ASC' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM (
    SELECT
        RISK_ID,
        RISK_SCORE,
        LAG(RISK_SCORE) OVER (ORDER BY RISK_RANK) AS PREV_SCORE,
        LAG(RISK_ID) OVER (ORDER BY RISK_RANK) AS PREV_RISK_ID
    FROM RISK.SUPPLY_CHAIN_RISK_RANKING
)
ordered_risks
WHERE RISK_SCORE = PREV_SCORE
  AND RISK_ID < PREV_RISK_ID;

-- V9: Validate the documented S017 / P104 / P01 scenario only if it qualifies.
SELECT
    'S017_P104_P01_REFERENCE_SCENARIO' AS CHECK_NAME,
    COUNT(*) AS QUALIFYING_RISK_ROWS,
    IFF(
        COUNT(*) = 0
        OR (
            COUNT(*) = 1
            AND MIN(SUPPLIER_ID) = 'S017'
            AND MIN(PART_ID) = 'P104'
            AND MIN(PLANT_ID) = 'P01'
            AND MIN(AVAILABLE_QUANTITY) = 8200
            AND MIN(SAFETY_STOCK) = 3000
            AND MIN(USABLE_QUANTITY) = 5200
            AND MIN(REQUIREMENT_QUANTITY) = 7350
            AND MIN(SHORTAGE_QUANTITY) = 2150
        ),
        'PASS',
        'FAIL'
    ) AS RESULT
FROM RISK.SUPPLY_CHAIN_RISK_RANKING
WHERE SUPPLIER_ID = 'S017'
  AND PART_ID = 'P104'
  AND PLANT_ID = 'P01';

-- V10: Manual/live side-effect validation for evaluator read-only behavior.
-- Do not run this block during static review. In DEV, execute it as a grouped
-- manual validation after sql/24 has been applied and before/after counts can
-- be compared in one worksheet.
--
-- BEFORE:
-- SELECT COUNT(*) AS APPROVAL_ROWS_BEFORE FROM WORKFLOW.INTERVENTION_APPROVAL_REQUEST;
-- SELECT COUNT(*) AS ACTION_ROWS_BEFORE FROM ACTION.INTERVENTION_ACTION_COMMAND;
--
-- READ-ONLY EVALUATOR CALL:
-- CALL DECISION.EVALUATE_SUPPLY_CHAIN_INTERVENTIONS('S017', 'P104', 'P01');
--
-- AFTER:
-- SELECT COUNT(*) AS APPROVAL_ROWS_AFTER FROM WORKFLOW.INTERVENTION_APPROVAL_REQUEST;
-- SELECT COUNT(*) AS ACTION_ROWS_AFTER FROM ACTION.INTERVENTION_ACTION_COMMAND;
--
-- EXPECTED: APPROVAL_ROWS_BEFORE = APPROVAL_ROWS_AFTER and
-- ACTION_ROWS_BEFORE = ACTION_ROWS_AFTER.

-- V11: Source mutation safety is validated statically before live execution.
-- sql/24_risk_intelligence.sql is intentionally additive: CREATE SCHEMA and
-- CREATE OR REPLACE VIEW in RISK only. Static review must confirm it contains
-- no INSERT, UPDATE, DELETE, MERGE, or TRUNCATE against business tables.

SELECT 'Phase 10 / 25_risk_intelligence_validation.sql ready for DEV execution' AS STATUS;
