/* ============================================================================
   SupplyChainIQ - PHASE 10b : PREDICTIVE STOCKOUT EARLY WARNING VALIDATION
   FILE    : 27_predictive_stockout_validation.sql
   PURPOSE : Read-only validation of the Predictive Stockout Early Warning
             backend and its non-interference with the confirmed Risk Radar.
   SAFETY  : SELECT only. No approval, execution, or source-data mutation is
             performed by this file.
   ============================================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SUPPLYCHAINIQ_DB;

-- V1: Model trained without per-series failures.
SELECT
    'TRAINING_LOGS_NO_FAILURES' AS CHECK_NAME,
    COUNT(*) AS TOTAL_SERIES,
    SUM(IFF(LOGS IS NOT NULL, 1, 0)) AS SERIES_WITH_LOG_MESSAGES,
    IFF(SUM(IFF(LOGS IS NOT NULL, 1, 0)) = 0, 'PASS', 'REVIEW')
      AS RESULT
FROM TABLE(RISK.SUPPLY_CHAIN_DEMAND_FORECAST_MODEL!SHOW_TRAINING_LOGS());

-- V2: Aggregate out-of-sample evaluation metrics (median is the trustworthy
-- summary here; MAPE is known to be unstable for intermittent/near-zero
-- demand and SMAPE/MAE should be preferred).
SELECT
    ERROR_METRIC,
    COUNT(*) AS N,
    ROUND(MEDIAN(METRIC_VALUE), 4) AS MEDIAN_VALUE,
    ROUND(AVG(METRIC_VALUE), 4) AS AVG_VALUE,
    ROUND(MIN(METRIC_VALUE), 4) AS MIN_VALUE,
    ROUND(MAX(METRIC_VALUE), 4) AS MAX_VALUE
FROM TABLE(RISK.SUPPLY_CHAIN_DEMAND_FORECAST_MODEL!SHOW_EVALUATION_METRICS())
GROUP BY ERROR_METRIC
ORDER BY ERROR_METRIC;

-- V3: Count of series excluded by the SMAPE > 0.5 quality gate.
SELECT
    'QUALITY_GATE_EXCLUDED_SERIES' AS CHECK_NAME,
    COUNT(*) AS TOTAL_SERIES,
    SUM(IFF(SMAPE > 0.5, 1, 0)) AS EXCLUDED_SERIES,
    ROUND(100.0 * SUM(IFF(SMAPE > 0.5, 1, 0)) / COUNT(*), 1) AS EXCLUDED_PCT
FROM RISK.FORECAST_MODEL_QUALITY;

-- V4: Persisted forecast covers exactly the 14-day horizon and no dates
-- fall before the reference date.
SELECT
    'FORECAST_HORIZON_BOUNDS' AS CHECK_NAME,
    COUNT(*) AS FORECAST_ROWS,
    COUNT(DISTINCT PART_ID || '|' || PLANT_ID) AS SERIES_CNT,
    MIN(FORECAST_DATE) AS MIN_FORECAST_DATE,
    MAX(FORECAST_DATE) AS MAX_FORECAST_DATE,
    MIN(REFERENCE_DATE) AS REFERENCE_DATE,
    IFF(MIN(FORECAST_DATE) >= MIN(REFERENCE_DATE), 'PASS', 'FAIL') AS RESULT
FROM RISK.FORECASTED_DEMAND;

-- V5: No PART_ID+PLANT_ID grain appears in both confirmed Risk Radar and
-- Forecasted Stockout Risk (confirmed-risk suppression, mandatory).
SELECT
    'NO_OVERLAP_WITH_CONFIRMED_RISK' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.FORECASTED_STOCKOUT_RISK f
WHERE EXISTS (
    SELECT 1 FROM RISK.SUPPLY_CHAIN_RISK_CANDIDATES rc
    WHERE rc.PART_ID = f.PART_ID AND rc.PLANT_ID = f.PLANT_ID
);

-- V6: No negative forecasted shortage.
SELECT
    'NO_NEGATIVE_SHORTAGE' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.FORECASTED_STOCKOUT_RISK
WHERE FORECASTED_SHORTAGE_QUANTITY < 0;

-- V7: No duplicate PART_ID+PLANT_ID rows in the output view.
SELECT
    'NO_DUPLICATE_GRAINS' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM (
    SELECT PART_ID, PLANT_ID, COUNT(*) AS CNT
    FROM RISK.FORECASTED_STOCKOUT_RISK
    GROUP BY PART_ID, PLANT_ID
    HAVING COUNT(*) > 1
) violations;

-- V8: Shortage formula reconciles exactly (no double counting - confirmed
-- demand is never part of this calculation).
SELECT
    'SHORTAGE_FORMULA_NO_DOUBLE_COUNT' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.FORECASTED_STOCKOUT_RISK
WHERE FORECASTED_SHORTAGE_QUANTITY <>
      GREATEST(FORECAST_DEMAND_QUANTITY - CURRENT_USABLE_QUANTITY - EXPECTED_INBOUND_QUANTITY, 0);

-- V9: Predicted stockout date is never before the reference date and is
-- within the 14-day forecast horizon.
SELECT
    'STOCKOUT_DATE_WITHIN_HORIZON' AS CHECK_NAME,
    COUNT(*) AS VIOLATION_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS RESULT
FROM RISK.FORECASTED_STOCKOUT_RISK
WHERE PREDICTED_STOCKOUT_DATE < REFERENCE_DATE
   OR PREDICTED_STOCKOUT_DATE > FORECAST_END_DATE
   OR DAYS_TO_PREDICTED_STOCKOUT < 0;

-- V10: Source data untouched.
SELECT
    'SOURCE_DEMAND_ROWCOUNT_UNCHANGED' AS CHECK_NAME,
    COUNT(*) AS ROW_CNT,
    IFF(COUNT(*) = 120000, 'PASS', 'REVIEW') AS RESULT
FROM DEMAND_PLANNING.DEMAND_HISTORY;

-- V11: Confirmed Risk Radar row counts unchanged by this phase.
SELECT
    'CONFIRMED_RISK_UNCHANGED' AS CHECK_NAME,
    (SELECT COUNT(*) FROM RISK.SUPPLY_CHAIN_RISK_CANDIDATES) AS CANDIDATE_ROWS,
    (SELECT COUNT(*) FROM RISK.SUPPLY_CHAIN_RISK_RANKING) AS RANKING_ROWS;

-- V12: Approval/action state unchanged by this phase (no evaluator or
-- workflow calls were made).
SELECT
    'APPROVAL_ACTION_STATE_UNCHANGED' AS CHECK_NAME,
    (SELECT COUNT(*) FROM WORKFLOW.INTERVENTION_APPROVAL_REQUEST) AS APPROVAL_ROWS,
    (SELECT COUNT(*) FROM ACTION.INTERVENTION_ACTION_COMMAND) AS ACTION_ROWS;

-- V13: Business-value check - top 10 earliest predicted stockouts, with
-- proof none of them exist in confirmed Risk Radar.
SELECT
    f.PART_ID, f.PART_DESCRIPTION, f.PLANT_ID, f.PLANT_NAME,
    f.CURRENT_USABLE_QUANTITY, f.CONFIRMED_DEMAND_QUANTITY,
    f.FORECAST_DEMAND_QUANTITY, f.EXPECTED_INBOUND_QUANTITY,
    f.FORECASTED_SHORTAGE_QUANTITY, f.PREDICTED_STOCKOUT_DATE,
    f.DAYS_TO_PREDICTED_STOCKOUT, f.LOWER_PREDICTION_BOUND, f.UPPER_PREDICTION_BOUND,
    IFF(EXISTS (
        SELECT 1 FROM RISK.SUPPLY_CHAIN_RISK_CANDIDATES rc
        WHERE rc.PART_ID = f.PART_ID AND rc.PLANT_ID = f.PLANT_ID
    ), 'IN_CONFIRMED_RISK (SHOULD NEVER HAPPEN)', 'NOT_IN_CONFIRMED_RISK') AS CONFIRMED_RISK_STATUS
FROM RISK.FORECASTED_STOCKOUT_RISK f
ORDER BY f.PREDICTED_STOCKOUT_DATE ASC, f.FORECASTED_SHORTAGE_QUANTITY DESC
LIMIT 10;

-- V14: Overall forecasted-warning counts.
SELECT
    'FORECASTED_WARNING_SUMMARY' AS CHECK_NAME,
    (SELECT COUNT(*) FROM RISK.SUPPLY_CHAIN_RISK_CANDIDATES) AS CONFIRMED_RISK_COUNT,
    (SELECT COUNT(*) FROM RISK.FORECASTED_STOCKOUT_RISK) AS FORECASTED_WARNING_COUNT,
    (SELECT COUNT(DISTINCT PART_ID || '|' || PLANT_ID) FROM RISK.FORECASTED_STOCKOUT_RISK) AS UNIQUE_FORECAST_GRAINS;

SELECT 'Phase 10b / 27_predictive_stockout_validation.sql complete' AS STATUS;
